### ISSUE TITLE
id and class selector

### ISSUE THREAD

**Issue by ukor** [KingSora/OverlayScrollbars#1]
Works fine when I use `$('body').overlayScrollbars({ });` or `$('div').overlayScrollbars({ });`

but nothing happens when i do this `$('#some_div_id').overlayScrollbars({ });` or this `$('.some_div_class').overlayScrollbars({ });`

**Comment by KingSora** [comment]
Well, thats indeed kinda weird. Can you provide a example? I've tested it on JSFiddle and it works perfetly fine. https://jsfiddle.net/hcmepy4p/

Please make sure your div is supported by the plugin: [https://kingsora.github.io/OverlayScrollbars/#!documentation/supportedelements](url)

**Comment by ukor** [comment]
I applied it on [materialize css side nav](http://materializecss.com/side-nav.html) . Here is a [JS fiddle](https://jsfiddle.net/o0wLrfL7/1/).

**Comment by KingSora** [comment]
The scrollbar is applied correctly. The problem is, you're applying the scrollbar to the false element.
Your wrapper div `#sd_n` does hold the `#slide-out` div but its position is fixed, so your wrapper div doesn't grow with the size of the `#slide-out` div.

Apply the plguin to `#slide-out`, this should fix everything. :) https://jsfiddle.net/o0wLrfL7/3/
