### ISSUE TITLE
Problem when transform scale

### ISSUE THREAD

**Issue by Dams591** [KingSora/OverlayScrollbars#102]
Hi guys,
First of all congrates for your plugin it looks amazing !
Just facing an issue when one of the ancestor has transform: scale

Here's how my page looks when scaled without overlayscrollbars

![image](https://user-images.githubusercontent.com/12731716/55329432-d6f54c00-548e-11e9-9453-45ef701e5247.png)

Now if I added .overlayScrollbars on the div that has overflow: auto
I have a useless scrollbar vertically ! same goes when scrollbar should be only vertical I get a horizontal one too.

![image](https://user-images.githubusercontent.com/12731716/55329514-0dcb6200-548f-11e9-885f-bf119a068d1a.png)

I first though it was my custom css but was able to reproduce here
https://jsfiddle.net/n8khsrt5/2/

As you see hozirontal scrollbars display for not reason and it's not visible if we take the transform scale under bigcontainer.

Any idea how to solve that ?
Thanks in advance,

**Comment by KingSora** [comment]
Good day!

Yes, I'm already aware of this bug, but it seems like quite a challenge to solve it. 
The conventional measuring methods `clientHeight`, `offsetHeight` and `scrollHeight` (and their `Width` counterparts) returns values which **aren't** scaled. Modern methods such as `getBoundingClientRect` will give you scaled values. But even if I replace all old methods with the modern one, this problem still doesn't seem to be solved, because `scrollHeight` doesn't have a real replacement.

To be fair, I've tried this real quick and haven't spend much time on this problem, so I can't give a definitive answer how complicated / time consuming this problem really is. 
I'll try my best to fix it as quick as possible though.

**Comment by Dams591** [comment]
Damn ! 
Any idea of a quick/dirty workaround ? was really hoping to use it in production in the next few days.

**Comment by Dams591** [comment]
Somewhere in the code if I could just say if handle height is 100% of viewport do not render scrollbar at all ?

**Comment by KingSora** [comment]
Well you could use this: [https://jsfiddle.net/qdaz0ynh/](https://jsfiddle.net/qdaz0ynh/), but please keep in mind this is just "quick and dirty".

**Comment by Dams591** [comment]
Seems to do the job for now ! Let me know when you got a proper update, amazing project !

**Comment by KingSora** [comment]
I'm happy to tell you, that I've managed to solve the problem in a appropriate way and the next version will definitely work with transformed / scaled elements. 
In the "quick and dirty" version above are some bugs (for example if you drag the scrollbar-handle, the positioning isn't correct as you move your mouse) which will also be fixed in the next release.

**Comment by Dams591** [comment]
Amazing job @KingSora ! Looking forward to 1.6.4 then !

**Comment by KingSora** [comment]
Alright! The new version [1.7.0](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.7.0) is now out. I've also created a [scaling demo](https://kingsora.github.io/OverlayScrollbars/#!demos/scale) which shows how the plugin is working with a scaled `host-element`.

**Comment by Dams591** [comment]
Amazing ! Upgrading version as we speak.
