### ISSUE TITLE
Best practices for fixed scrolling

### ISSUE THREAD

**Issue by main-gi** [KingSora/OverlayScrollbars#103]
What's the best way to make a fixed sidebar with scrolling? Example for what it'd look like: https://jsfiddle.net/pcmsvy2a/1/ (unfortunately the resource js doesn't seem to work, but it should serve as a template anyway of what it would look like)

Basically, I want both scrollbars to turn into overlay scrollbars.

In my project, trying to do this doesn't work, because the sidebar's position becomes relative, and I get this in the console as well:

> This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

I ended up sorta-not-really fixing it with a " * nav {position: fixed !important;} ", but it seems like a hacky solution. The scrollbars also overlap when that happens. Is there a better way?

**Comment by KingSora** [comment]
Good day!

This seems more like a general question than a issue related to the plugin. I'm trying to keep the github issues as "clean" as possible so next time please use platforms like [Stackoverflow](https://stackoverflow.com/) for plugin unrelated questions.

But I'll provide a answer anyway! - In my oppinion such a layout is heavily dependent on your needs and requirements. But a simple and clean layout would be something like [this](https://jsfiddle.net/9sz5efh2/).

**Comment by main-gi** [comment]
Well, I thought it was related because the native scrollbars displayed properly with position: fixed. But, thank you! (I also didn't realize it was possible to call OverlayScrollbars on two different elements, I thought it could only be initialized once.)

**Comment by KingSora** [comment]
I'm glad I could help! You can initialize `OverlayScrollbars` on as many elements as you want, there is no limitation. 

I forgot one thing: you can ignore the warning in the console. The warning is appearing because I'm changing the scrollbar-handles position inside a `scroll` event (which has to be like this, because else the handle would be on the top all the time). Unfortunately I can't get rid of the warning... as soon as there is a possibility to avoid this warning I'll implement it.
