### ISSUE TITLE
'display: grid' not supported?

### ISSUE THREAD

**Issue by plagasul** [KingSora/OverlayScrollbars#108]
OverlayScrollbars seems to break 'display:grid' containers.

The full CSS of the container is:

```
.home-grid-container {
  align-self: flex-start;
  display: grid;
  grid-template-columns: min-content 2fr 1fr;
  grid-gap: 0px;
  width: 97%;
  height: 100%;
  overflow-y: auto;
  overflow-x: hidden;
  font-size: 12vh;
  line-height: 1;
}
```

**Comment by KingSora** [comment]
Good day!

I haven't tested the plugin with grid containers yet, but I know that some users already used it with `display: grid`. Since the plugin is changing your DOM, please apply the grid styling to the added `.os-content` element. You should definitely try to change your styling to match the newly generated DOM, because your `.home-grid-container` element isn't the parent of your `grid-items` anymore. You can read more about the DOM change in the documentation [here](https://kingsora.github.io/OverlayScrollbars/#!documentation/domelements) or you can simply use the DeveloperTools DOM Inspector to check it out.

**Comment by plagasul** [comment]
That clarifies it, thank you.
I've solved it with a wrapper div.
Thanks again.

**Comment by KingSora** [comment]
Glad I could help!
