### ISSUE TITLE
Scrolling not working on items with property flex: none;

### ISSUE THREAD

**Issue by jsieler** [KingSora/OverlayScrollbars#11]
I'm trying to get sroll working on element with css property `flex: none;`. See following demos:
That is where box is collapsed: https://sieler.im/scroll/test1.html
But, i wonder why? Height isn't calculated properly?

**Comment by KingSora** [comment]
Yeah, the problem is, that the plugin doesn't know about your flex layout. 
The created DOM has to fulfill certain requirements. Unfortunately this isn't the case if you initialize the plugin directly into a flexbox layout container.

The solution: 
Add a child div into `#SCROLL`, which is holding all your content. (it should have `height: 100%` and `width: 100%` to fill the whole parent container) Then initialize the plugin to the added child container.
If you need a example please let me know.


I think it would be a huge effort to make the plugin "flexbox capable" and the code would grow pretty much. I don't think it would be a good trade to do that if you can use this "workaround" and everything is just working.

Of course if you find any bugs with this workaround please let me know.

**Comment by KingSora** [comment]
Here you go: https://jsfiddle.net/f205jbbm/3/

**Comment by jsieler** [comment]
Hm, still no... https://sieler.im/scroll/test3.html

**Comment by KingSora** [comment]
Please change `style="height : 100%` to `style="height : auto`.

**Comment by jsieler** [comment]
If on #OS, then done. Still same.

**Comment by KingSora** [comment]
Are you sure? It's working here. Which browser are you using?
I've tested it with Firefox, Chrome, IE11 and Edge. [Screenshot](https://i.imgur.com/nR6AjNZ.png)

**Comment by jsieler** [comment]
Ehm, you're missing the scrollbar, or? Using last FF.

**Comment by KingSora** [comment]
Uhm I don't understand, the scrollbar will never appear unless you set a max-height. For example `max-height: 100px`. On your first test, don't initialize the plugin and set `overflow: auto` on `#SCROLL`. Even the native scrollbar wont appear.

**Comment by jsieler** [comment]
My goal is to make a "block" element, which will have height of its content. When this blocks height is higher than parent element, scroll should appear.

**Comment by KingSora** [comment]
Thanks to you I've found a different bug. You tried to add elements to `#OS .os-content` and the plugin didn't update itself. This is actually a bug, and I'll fix it in the next version. If you wan't a quick and dirty fix, execute `$('#OS').overlayScrollbars().update();` after each append to `#OS .os-content`.

**Comment by jsieler** [comment]
This is what i'm trying to get  https://sieler.im/scroll/test0.html

**Comment by KingSora** [comment]
I had quite a struggle, but here you go: https://jsfiddle.net/knpegmt8/22/

**Comment by KingSora** [comment]
Unfortunately Firefox, Chrome and pretty much every browser is implementing flexbox differently, so the above fix will only work in Firefox.

I did a more elegant version which is working in all browsers. I only thought a bit too complex, the solution is actually pretty simple: https://jsfiddle.net/knpegmt8/35/
Please use this solution.

**Comment by KingSora** [comment]
Are there any updates on this issue, did I solve your problem?
