### ISSUE TITLE
Lag when scrolling with mouse wheel click 

### ISSUE THREAD

**Issue by Devstackr8** [KingSora/OverlayScrollbars#116]
Hi KingSora and contributors, first of all, thank you for this amazing library. 

I am using this library for a list of of items in my sidebar. Everything works great, but I have noticed that when I use the mouse wheel click to scroll it is quite janky. I have tested this in Chrome and Firefox and the issue isn't present in Firefox, just Chrome.

![mouse wheel click scroll](https://user-images.githubusercontent.com/42569312/59047129-313dcf00-887b-11e9-90d5-f6ef9635823d.png)

I was just wondering if there is a possible fix - many thanks in advance!

Note: I experience the same thing when I scroll the demo website using the mouse wheel click.

**Comment by KingSora** [comment]
Good day!

Thats pretty weird and I couldn't really notice something like this on my end. Whats OS are you testing on?

**Comment by Devstackr8** [comment]
@KingSora Good day! Thank you for your prompt response. I'm using Windows 10 with Google Chrome.
I recorded a clip of me scrolling the docs website: https://youtu.be/wrf6m3FULZs
It is quite difficult to see the janky scroll there (but it is fairly visible mid way through that video), its much easier to 'feel' that there is something off about the scrolling experience.

After some more research I think this may be an issue with the way chrome handles scrolling with the mouse (it uses the main thread). Its a relatively minor issue and all other scrollbar libraries I have seen have this.

**Comment by KingSora** [comment]
@Devstackr8 Unfortunately I'm not sure how to fix this, since I'm not even sure what's causing this issue. My theory is, that the position update of the scrollbar handles could be the potential cause. But if thats true, there is currently no way to fix this problem. A possible fix could be a new feature called [Scroll Timeline for Web Animations](https://www.chromestatus.com/feature/6752840701706240). With this API it could be possible to update the handle positions without actually changing the CSS on every scroll, but since this feature isn't ready yet, its hard to tell whether ist's really possible.

There is a thing you could try though. Create a new CSS rule which looks like this:
```CSS
.os-scrollbar-handle {
   will-change: transform;
}
```
Maybe, and thats a big maybe, this will cause some performance gains, but I'm not sure.
