### ISSUE TITLE
Viewport doesn't resize when <details> element is expanded

### ISSUE THREAD

**Issue by axelstudios** [KingSora/OverlayScrollbars#119]
When clicking the `<summary>` element inside of a `<details>` element, OverlayScrollbars doesn't recognize that the page size has changed and requires a deferred hard update to show the correct scrollbar visibility/size.

Minimal example (with code to get it working commented out):
https://stackblitz.com/edit/overlayscrollbars-details?file=index.js

**Comment by KingSora** [comment]
Good day!

Thanks for your very clear example. I've tested it, and this is happening because the used `MutationObserver` doesn't recognize a change, because it's not listening on the correct property which is `open`. I haven't tested OverlayScrollbars with a `details` element inside yet, so thanks for this report!

**Comment by KingSora** [comment]
By the way, in case you want to fix this issue temporary until the fix is out, you can set the option `autoUpdate : true`.

**Comment by axelstudios** [comment]
Ah that's handy, thanks!

**Comment by KingSora** [comment]
Alright, the bug should be fixed in [v1.7.3](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.7.3), please confirm it so I can close this issue.

**Comment by axelstudios** [comment]
Confirmed working, changing package.json in my stackblitz example to 1.7.3 resolves the issue.  Thanks!

**Comment by KingSora** [comment]
Glad I could help!
