### ISSUE TITLE
Virtualization

### ISSUE THREAD

**Issue by Citriik** [KingSora/OverlayScrollbars#125]
Hello,

I've just switch from mCustomScrollbar to this really good OverlayScrollbars but I have a problem, 
I need to virtualize a container because I have a lot of objects to load and it's not possible in one call. So with mCustomScrollbar this was not a problem but with OverlayScrollbars it's behaving really strangely.

Here is a JSFiddle to show you what's happening (except here it's scrolling to the bottom and in my case it's scrolling up but I don't think it matters): https://jsfiddle.net/3yzdv5up/14/

Thanks for your help :)

**Comment by KingSora** [comment]
Good day!

Since `OverlayScrollbars` uses the browsers `native` scroll functionality, and `mCustomScrollbar` doesn't (it changes the scroll-offset through CSS) there are fundamental differences between the plugins.
 
I've tested your script without any scrollbar plugin to check whether it works properly, but it turns out it acts exactly the same as if you would use `OverlayScrollbars`: https://jsfiddle.net/jtyhb3qn/
So it seems like your script did only work because you was using `mCustomScrollbar` and it wouldn't work without it. Therefore it's not really a bug of `OverlayScrollbars`, I hope thats logical reasoning.

I've found one small but maybe important mistake in your example:
```JavaScript
for (let i = 0; i < total; i++) {
  elements.push($('<p>TEST<p>'));
}
```
You never close the `p` tag, instead u have two opening `<p>` tags. With this the browser adds more `p` tags than you would expect, please check it out in the developer tools. But even after I've fixed this mistake the weird scroll behavior wasn't fixed.

In the past there was already a dicussion about virtual lists (#49) and OverlayScrollbars works pretty good with [HyperList](https://github.com/tbranyen/hyperlist), heres a example: [https://jsfiddle.net/Lesgjxbn/](https://jsfiddle.net/Lesgjxbn/) maybe its worth to take a look.

**Comment by Citriik** [comment]
Hello, 

Thank you for your answer that's exactly what I was looking for !

**Comment by KingSora** [comment]
Glad I could help!

**Comment by Citriik** [comment]
Hi, 

I've found an issue but I'm not sure if it's related to OverlayScrollbars or HyperList, when you scroll to the end and without stopping scrolling you scroll up the list get stuck.
Here is a JSFiddle where I managed to reproduce the issue: https://jsfiddle.net/zv2sb3hw/109/

Thanks for your help :)

**Comment by KingSora** [comment]
Good day @Citriik 

I've replaced `OverlayScrollbars` in your example with a simple `div` so I can test wether the bug appears without the plugin... and it does. At least on my machine, you can test it here: https://jsfiddle.net/eksr695p/

So it seems its related to `HyperList`, but its also could be a browser issue, its hard to tell.

**Comment by Citriik** [comment]
Thanks for you answer I will ask on the HyperList github page for assitance :)

**Comment by xmsz** [comment]
HyperList太复杂了 大家有没有其他差价推荐
