### ISSUE TITLE
Textarea resize does not work if it inside scrollable div in Firefox 67+

### ISSUE THREAD

**Issue by Assizes** [KingSora/OverlayScrollbars#127]
If container height is set to anything else than to specific px height, plugin interrupts textarea resize In Firefox 67+
https://jsfiddle.net/6gmf73cs/1/

**Comment by KingSora** [comment]
Good day!

I see the problem, but there isn't really anything I can do about it... Do you might have a idea? 

You could initialize OverlayScrollbars to the `textarea` element directly and set the option `resize : 'both'` to workaround this issue. Since it's  working in Chrome, I assume this is a special bug to firefox and how the browser has implemented the `resize` functionality for textareas.

**Comment by Assizes** [comment]
Thanks for the workaround, It did not come to my mind to try to add OverlayScrollbars also to textarea to see if it solves this issue.
