### ISSUE TITLE
Sticky header and footer

### ISSUE THREAD

**Issue by Citriik** [KingSora/OverlayScrollbars#129]
Hello,

I'm trying to implement sticky header and footer with this plugin and it's working fine on Chrome but if I try it on Firefox on even worse on Edge then there is some kind of stuttering in the scroll. I discovered that there is a delay on the onScroll callback on Firefox and Edge. Do you have a solution for this problem ?

I've created a JSFiddle that show the problem: https://jsfiddle.net/86L0y3qb/7/

Thanks for your help :)

**Comment by KingSora** [comment]
Good day!

I'm afraid, but this has nothing to do with the plugin... If you create the same example but just without `OverlayScrollbars`, the same thing should happen: [https://jsfiddle.net/8djpuoht/](https://jsfiddle.net/8djpuoht/) This problem is occuring because you are linking the `scroll position` to a `css` property (`transform` in your case). This is something you shouldn't do... You can read more about it [here](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects).

Currently theres no workaround or something and the shuttering you mentioned depends heavily on you hardware / browser (fast hardware / browser = less shuttering). In the future there will be a feature called [Scroll Timeline for Web Animations](https://www.chromestatus.com/feature/6752840701706240) which could solve the issue.

**Comment by Citriik** [comment]
Hello,

Thanks for your response, I realized that in order to this I had to `position: sticky` but I have to support IE11 so there is no way for me to use this scrollbar in a specific page but it's fine everywhere else.
