### ISSUE TITLE
Angular - AoT compilation support

### ISSUE THREAD

**Issue by cyril-drouet** [KingSora/OverlayScrollbars#132]
When I try to build in produciton mode, I get the following error:
Unexpected value 'OverlayscrollbarsModule in D:/Dev/Boulanger/OverlayScrollbars-master/packages/overlayscrollbars-ngx/example/node_modules/overlayscrollbars-ngx/dist/types/overlayscrollbars.module.d.ts' imported by the module 'AppModule in D:/Dev/Boulanger/OverlayScrollbars-master/packages/overlayscrollbars-ngx/example/src/app/app.module.ts'. Please add a @NgModule annotation.

The error happens with the sample "packages/overlayscrollbars-ngx/example"

**Comment by KingSora** [comment]
Good day!

After a long research I've finally figured out why this error is happening when you try to build with `--prod` for production. Its happening because currently `overlayscrollbars-ngx` doesn't support `AoT` compilation because the corresponding `*.metadata.json` is missing. I wasn't aware of that and will fix this in `v0.1.1` today or tomorrow. 

In the meantime if you don't need `AoT` compilation you can run the command like:
```sh
ng build --prod --aot=false --build-optimizer=false
```

**Comment by KingSora** [comment]
Alright, the bug if fixed in [overlayscrollbars-ngx v0.1.1](https://www.npmjs.com/package/overlayscrollbars-ngx)!
