### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by LuisPerez94** [KingSora/OverlayScrollbars#133]
Good day. 
I'm using Next js for my current project and I have issue relationed with this library. It's only happen in my production enviroment. The issue is as following

![image](https://user-images.githubusercontent.com/9045933/62641230-ceaf9080-b908-11e9-96e3-68b2d83d35a5.png)

It's important to note that i´m using the React wrapper for this implementation.

I have been researching in the repository and I think it is because the listeners are generated but they are not closing. Can anyone tell me if this is and bug and how can we fix it.

This is my first issue report, so if i'm missing somenthing to continue please tell me.

**Comment by maritzacarter** [comment]
I have the same issue :(

**Comment by KingSora** [comment]
Good day!

Is there any line number or something similar in the error? Because before I'll research this I wanna make sure this is caused _by_ the library and not caused _by how you use_ the library. Also is this error popping up instantly or does it appear after you do something special / after a certain time?

**Comment by KingSora** [comment]
@LuisPerez94 Are there any updates on this issue?

**Comment by KingSora** [comment]
I'll close this issue due to inactivity. In case you've something new, feel free to reopen it!
