### ISSUE TITLE
Can't get vue version to work?

### ISSUE THREAD

**Issue by whoisme555** [KingSora/OverlayScrollbars#134]
I've been reading through the docs but can't seem to get it to show or scroll.

![image](https://user-images.githubusercontent.com/50149901/63200519-90744880-c04f-11e9-91a9-24c9f2ba0905.png)

This is my html, where I wrap my content in the overlay scrollbars component.

I've installed both the overlayscrollbars and overlayscrollbars-vue npm package, and am importing the vue one like so

![image](https://user-images.githubusercontent.com/50149901/63200551-b00b7100-c04f-11e9-8109-f7c5ada529c1.png)

And then I'm using the component locally like so

![image](https://user-images.githubusercontent.com/50149901/63200568-c44f6e00-c04f-11e9-8329-563df46f347b.png)

It's adding to the dom and using the correct stylesheet, but I still can't scroll, nor is it visible
![image](https://user-images.githubusercontent.com/50149901/63200795-9159aa00-c050-11e9-96e6-75824794bd28.png)

I'm making sure to import the css before the js, but still can't get it running.  Any idea what I'm doing wrong?

**Comment by KingSora** [comment]
Good day!

It looks like the `overlay-scrollbars` container has an implicit `height: auto` style (thats the default CSS value if you don't set it to something else). So the container will expand always with your content and so the scrollbars won't show. Try to set the height or max-height to something like `height: 100%`, `height: 250px` or the `max-height: 250px` so the container can generate a overflow.

**Comment by whoisme555** [comment]
Setting height 100% on os-host fixed it. Is this a bug or am I just using it incorrectly?

**Comment by KingSora** [comment]
Well, this issue is related to how `html` and `css` works. If you replace the `overlay-scrollbars` element with a regular `div` element with the style `overflow: auto` it would act exactly the same. The implicit `height: auto` style (without an `max-height` style) simply says: **"well, I guess my height is `auto`, so I'll always grow with my content until infinity"**. The `height: auto` style on the other hand says: **"my height is always `100%`, so if my content is greater than that, its an overflow and scrollbars could appear"**.

**Comment by whoisme555** [comment]
I guess my question is - shouldn't the scroll bar come with appropriate styling to begin with? It seems weird that the scroll bar container wouldn't have its height constrained, by default, to the height of its parent element via height: 100%. I'm just trying to imagine a scenario in which I would be using a scroll bar component without the sole purpose of saying "everything within this element should be scrollable when its height exceeds the available height". For now, I've just created a Vue component wrapper that sets that height to 100% and passes in my default styles in the template, but I'm curious about the logic behind requiring height to be explicitly set for it to scroll, rather than just inheriting the height of the parent

**Comment by KingSora** [comment]
The answer is no, because if I would set the height to `100%` by default, it obviously wouldn't match the default value `auto` of a regular `div` element. My approach is this: the library should be styling wise as close to a native `div` element as possible, so other people doesn't really need to know much about the library itself to style their app. Obviously this isn't entirely possible, but in your case it would just work if you'd thread it as if it would be a `div` element.

In your app, you could also replace your `div` with the id `dynamichomepage-layout-page-container` with the `overlay-scrollbars` component (you need to give it the `id` obviously) and everything would also just work, even without the style of `height: 100%` because you propably set the height of the element to something in your css. And thats exactly what the plugin should do, it should just blend with your app with the existing rules of the web. Instead of setting my own rules, I'll just use the rules everyone is familiar with.

**Comment by whoisme555** [comment]
Oh, I hadn't realized that it wasn't intended to be nested under a container div, but rather used as the container div with its own set of styling. Sorry for my misunderstanding, and thanks a lot for the explanation!

**Comment by KingSora** [comment]
No problem, you're welcome!
