### ISSUE TITLE
Bootsrap Modal is not working

### ISSUE THREAD

**Issue by princejohnpeal** [KingSora/OverlayScrollbars#14]
Hi, thank you for your awesome plugin. I like it but there is a small bug whois is the bootstrap modal is not working properly after installing your plugin. When I click the modal button it's open but never close and on the top of the modal, there is a black mask.  Hope I will get a solution soon. 

Thank you

**Comment by KingSora** [comment]
Hi, can you provide a small demo (for example on www.jsfiddle.net)? 
I need more info to solve this problem.

To which element have you initialized the plugin?

**Comment by princejohnpeal** [comment]
I have initialized on the body and on parent div but both of them failed. 
I am unable to put codes to jsfiddle but here is two images, hope it will helps you. 

Thank you for your awesome work. 

https://imgur.com/3fvLzes
https://imgur.com/YKEinxi

**Comment by KingSora** [comment]
Alright, the reasen why this is happening, is because of the functionality of the Bootstrap modals.
Bootstrap is adding a div with the class `modal-backdrop fade show`. This div is above all other divs, it is also above the divs which are created by my plugin. Thats why the content which is wrapped inside of the divs of my plugin is also behind the `modal-backdrop` div. 

The solution is easy, just create a wrapper div, and put your content in there. I've created a small demo for you: https://jsfiddle.net/ebgzmz4s/1/
I've used Bootstrap 4, but it shall work also with Bootstrap 3.
I am afraid there is no other workaround, because you can't tell bootstrap to create the beackdrop inside of the plugins `os-content` div. If this would be possible, then this would be the "better" fix.

**Comment by KingSora** [comment]
@princejohnpeal Did I solve your problem? Any updates on this issue?

**Comment by KingSora** [comment]
I'll close this issue, if I haven't solved your issue please don't hesitate to contact me.

**Comment by Abdulmanan0315** [comment]
Please provide a solution for bootstrap modal.For example if we initiate it on body then we should place the modal outside of the body element ! Please provide a jquery solution that works!This issue should not be closed yet

**Comment by KingSora** [comment]
@Abdulmanan0315 I've explained the solution to this problem above in full detail and even provided a example fiddle. In case this soltion isn't working for you, could you create a small example fiddle with your setup which demonstrates your problem? - I'll investigate then into it as soon as possible.

**Comment by Abdulmanan0315** [comment]
Indeed this solution is working but if their will be a jquery solution i will be happily using it because i am trying to use this on body and my modal gets dark (similar issue to @princejohnpeal )

**Comment by Abdulmanan0315** [comment]
Or any CSS solution for this the thing is i cant just place my modals outside of the body and i want to apply overlayscrollbar to body .On placing my modals outside, i cant get things to work.
This is just the main problem that i am currently facing and not being able to use this plugin although this is almost perfect.

**Comment by Abdulmanan0315** [comment]
<img width="922" alt="boot" src="https://user-images.githubusercontent.com/20532497/47964984-be5d4300-e062-11e8-82c6-4221d43b0dbf.PNG">

**Comment by Abdulmanan0315** [comment]
[](https://jsfiddle.net/abdulmanan0315/zm29ec3b/2/)
