### ISSUE TITLE
Bootstrap modal is not working inside of target div

### ISSUE THREAD

**Issue by shibbirweb** [KingSora/OverlayScrollbars#140]
[OverlayScrollbar.zip](https://github.com/KingSora/OverlayScrollbars/files/3604779/OverlayScrollbar.zip)
![image](https://user-images.githubusercontent.com/35910749/64773329-fc28d300-d573-11e9-87c1-5bf203cd4f51.png)

Modal unable to click if modal in target element. Can anybody give me solution??

**Comment by KingSora** [comment]
Good day!

Sorry for the late response, I didn't have much time the last days.
This issue is the same as described in #14, please read my response there to fully understand the solutions (there are 2 possible solutions). I've attached the both possible solutions below.

[Fix.zip](https://github.com/KingSora/OverlayScrollbars/files/3615108/Fix.zip)
