### ISSUE TITLE
css-modules support for react?

### ISSUE THREAD

**Issue by Media-Evil** [KingSora/OverlayScrollbars#145]
Something like this:
```
import css from './style.scss'

<OverlayScrollbarsComponent
  options={{
    styleMap :  css
  }} 
>
```
or 
```
import { foo, bar } from './style.scss'

<OverlayScrollbarsComponent
  options={{
    styleMap :  {
      "os-host": foo,
      "os-scrollbar": bar
    }
  }} 
>
```
global styles makes this... less conveniently usable with css-modules 
or maybe u have any suggestions?

**Comment by KingSora** [comment]
Good day!

May I ask why you need css-modules? The styles are meant to be global, because there are also styles included which aren't applied to the component but also to special elements like the `html` and `body` element. Also global styles shouldn't interfere with css-modules or other css solutions because they shall only be imported _somehow_ into your project.

**Comment by Media-Evil** [comment]
Hi. Indeed. I can't counterargument.

**Comment by KingSora** [comment]
@Media-Evil Just to be clear, its not about arguments here, but just how I see the thing. In case you have a concrete usecase and its something you can't achieve with global styles, you can mention it. I'm open to everything!
