### ISSUE TITLE
no means to make viewport unfocusable

### ISSUE THREAD

**Issue by Media-Evil** [KingSora/OverlayScrollbars#153]
Some browsers (Firefox) [make elements with overflow focusable via `Tab` key](https://bu754.csb.app/). This behaviour can be overwritten with `tabindex` attribute, but it's quite tedious to reach these elements trough `OS instance`. 

Please consider adding an option to specify the `tabindex` attribute for viewport element through public API.

**Comment by KingSora** [comment]
Good day!

Thanks for the report, I didn't notice this behavior at all. It also seems only to appear if the content is overflowing so a `overflow: auto` style without a actual overflow won't get the focus.

I think this is something only Firefox does. I'm also not sure how to handle this, because I think adding a extra option for such a small thing isn't the right way to go. I have a different suggestion:

The `viewport` element will inherit the actual `tabindex` attribut of the `host` element, so they both are in sync. In this case if you change the tabindex before the initialization to `-1` the viewport will also initialize with `tabindex="-1"`. The same will happen if you should change it after initialization.

**Comment by KingSora** [comment]
This is now implemented as of  [version 1.11.0](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.11.0)!
