### ISSUE TITLE
Place scrollbar outside of the scrollable container

### ISSUE THREAD

**Issue by jonrz** [KingSora/OverlayScrollbars#158]
I was just trying to get the scrollbar outside of the scrollable container, and I had to hack it so:

.os-host-overflow {	overflow: visible !important;  }
.os-scrollbar.os-scrollbar-vertical {	transform: translateX(13px);  }
.os-scrollbar.os-scrollbar-horizontal { transform: translateY(13px); }

![image](https://user-images.githubusercontent.com/25874295/69114255-3eb4e180-0ac8-11ea-8a39-22fbdbb23c0f.png)

However, I am still not sure if this will break anything in there, but my tests shows no breaks so far.
I would like to suggest a way of placing the scrollbar outside of the scrollable container, either by removing the overflow hidden in the outermost container, or placing the scrollbar nested a level above, and pad the container.

**Comment by wza666** [comment]
@jonrz fix your import order:

1. import 'overlayscrollbars/css/OverlayScrollbars.min.css';
2 import OverlayScrollbar from 'overlayscrollbars/js/OverlayScrollbars.min';

**Comment by KingSora** [comment]
Good day!

Sorry for the late answer, but I've overlooked your issue. The plugin doesn't officialy support the placement of the scrollbars outside of the host-element. If you just need some space between the scrollbars and your content, I would recommend to use the `paddingAbsolute` option to make that happen. I've created a small showcase of this option the [FAQ](https://kingsora.github.io/OverlayScrollbars/#!faq) (4th question from the top).

To your "hack", it's possible that this change:
```css
.os-host-overflow { overflow: visible !important; }
```
Can cause unexpected behavior, but only in very specific cases. If everything is running without any noticable error, then it's fine and you can keep the hack. But please be aware of potential (hard to test and trace back) errors because of this. These can occur on very exotic styling / DOM.
