### ISSUE TITLE
Bootstrap modals not working when the webpage body uses overlay scrollbars.

### ISSUE THREAD

**Issue by Ulsah** [KingSora/OverlayScrollbars#159]
Hello there,
I've been facing an issue while trying to use overlay scrollbars with bootstrap modals. I understand that OS works with bootstrap modals but in my case it doesn't.

I use OS for my body and it works fine. But after that if I try to launch a modal window, the window pops up and stays inactive there behind a faded background. This happens even without the usage of OS on modals. And when I actually use OS on modals, just like the modal window it appears but remains inactive in the background. The thing to note is that the OS used for body remains active and usable after the modal window pops up in its inactive stage.

Here is the link for the demo: https://jsfiddle.net/1L4fbvq9/

I hope you will look into it. Thank you.

**Comment by KingSora** [comment]
Good day!

There was a few issues in the past related to bootstrap modals. Please check them out first and give feedback whether u found something usefull: #140 #118 and #14

**Comment by Ulsah** [comment]
Thank you for the response.
The code shown in https://jsfiddle.net/zm29ec3b/3/ sort of works but one problem still persists. My modal dialog is scrollable. The modal window is no more inactive, but when it pops up, OS is replaced by the default browser scroll bar. I have shown the example here https://jsfiddle.net/cL28hsfw/1/
I don't know if this problem was fixed. If it was, please tell me how.
Thank you.

**Comment by KingSora** [comment]
The problem is, OverlayScrollbars isn't replaced by native scrollbars, but a new element is generated by bootstrap to which OverlayScrollbars isn't initialized and thus the native scrollbars are shown.
To fix this, you can simply initialize OS to the modal wrapper element: https://jsfiddle.net/vk6uL2r8/

The important thing here is the order in which you load the CSS, because OverlayScrollbars must not overwrite the bootstrap styles. So Load OverlayScrollbars.css first and Bootstrap.css second.

**Comment by Ulsah** [comment]
That makes sense. The code you provided in previous comment helped and modals are working fine now. Thank you so much for your help.

**Comment by KingSora** [comment]
Glad I could help!
