### ISSUE TITLE
Textarea in Angular

### ISSUE THREAD

**Issue by LexxDer** [KingSora/OverlayScrollbars#167]
Good day!
How can i use textarea in angular?

**Comment by KingSora** [comment]
Good day!

Currently all the wrapper versions (`react`, `vue` & `angular`) of the plugin don't support the `textarea` element. Until I've implemented that feature you can create your own textarea `component` / `directive`.

**Comment by cesarbmolina** [comment]
Do you plan to pass the textarea soon to the angular library?

**Comment by KingSora** [comment]
@cesarbmolina Currently I don't know exactly when it will be happen or how I'll implement it. I'm sorry!

**Comment by Eric24** [comment]
@KingSora - We might take a shot at it. Is there a specific issue you've identified that makes this particularly difficult or is it just a lack of time to look at it? Also, I assume the same goes for iframe support?

**Comment by Eric24** [comment]
@KingSora - Will you accept a PR for us to work on this? Do you have any specific requirements for contributed code?

**Comment by KingSora** [comment]
@Eric24 so for the late reply!
I didn't implement it yet, because I wasn't sure how to implement it in a way, so that other frameworks like `react` and `vue` can implement it in the same way. I already made some preparations for this.

Of course you can contribute and create a PR, but since the requirement is that `react` and `vue` must implement it in the same way, you must not use something like `directives` in angular. Conecpts like this doesn't exist on other frameworks. 

The other things which should be the case:
- Use Typescript (shouldn't be a problem in angular)
- The component should have the same properties / attributes like a regular textarea component (https://www.w3schools.com/tags/tag_textarea.asp)
- The plugin has to update after you changed the `value` attribute in the code.
- There must be a method with which you can get the current `value` of the textarea.
- The textarea component should have the same methods as the regular component (`osInstance`)
 and so on.

**Comment by KingSora** [comment]
`v2` released today where the initialization to `textarea` is not implemented yet. With its released `overlayscrollbars-ngx` where the initialization to `textarea` will be possible once its implemented in `v2` thus I'll close the issue for now
