### ISSUE TITLE
Use absolutePadding and ability to scroll on padding

### ISSUE THREAD

**Issue by 414m0d3** [KingSora/OverlayScrollbars#184]
I have a component that I'm using a padding-top, however I also need the user to be able to scroll while the mouse in that padding. Retaining the the padding-top is only possible with absolutePadding (otherwise the padding-top will scroll with content). However with absolutePadding users are unable to scroll in any of the padding areas.

Is there a way to keep absolutePadding and enable scrolling in padded area.

**Comment by KingSora** [comment]
Good day!

I understand your problem, but it can't be fixed. The padding absolute feature works by adding padding to the parent element of the `viewport` element to essentially shrink the `viewport`. And since you can only scroll within the `viewport` it can't really be changed. MAYBE and thats a big maybe there's a way to create a workaround by catching the `scroll` event on the `padding` element and somehow forward it to the `viewport`, but I really don't know whether this can work without bugs.
