### ISSUE TITLE
Scrollbars in flexbox container

### ISSUE THREAD

**Issue by skoropadas** [KingSora/OverlayScrollbars#197]
Hi, I have some issue with the flexbox container.
the native scrollbar displays normally, but the overlayscrollbar has a wrong width.
I tried to adding the os-host-flexbox class, but it still doesn't work properly.
jsfiddle demo - https://jsfiddle.net/tkehg9L3/1/

**Comment by KingSora** [comment]
Good day!

Thanks for your report and the example. This behavior is related to how I'm measuring the available size if the container has dynamic `width`. Currently the value is equal to the text wrapped as small as it can in the inline direction without causing an overflow, doing as much soft-wrapping as possible. Thats why the container appears so short. The fix for your issue in particular would be the opposite,  the text display as wide as possible, doing no soft-wrapping, even if an overflow was caused.

Fortunately this feature is implemented into modern browsers and it is called `Intrinsic Size` ([documentation](https://developer.mozilla.org/en-US/docs/Glossary/Intrinsic_Size)), in particular the `max-content` value. Unfortunately it is also in experimental stage and according to MDN you shouldn't use it in production code. I've made a demo for you: https://jsfiddle.net/cpyfnks0/

I also have no workaround for your case, it will work if you specify a `min-width` though.. I need to think about it and I'll consider to implement the `max-width` fix if it doesn't break anything other in the plugin.

**Comment by skoropadas** [comment]
thank you, it was very informative. I'm making the custom scrollbar in a tooltip, and in the demo I showed you how it works in my case, so I can't make the custom scrollbar in the tooltip if the content is very large. I would be very grateful if you could find a solution.

**Comment by KingSora** [comment]
As I suggested, setting a `min-width` could be a possible workaround for the meantime... But I understand that in case of tooltips this workaround also isn't the best as it isnt very dynamic.

**Comment by skoropadas** [comment]
yeah I know, but for me, dynamic width/height is very important in that case, so I use the native scrollbars until there is another way to use a your custom scrollbar

**Comment by KingSora** [comment]
@skoropadas good news, I'm currently working on the new version (`v1.12.0`) and this feature will most likely ship with that version. Since this is a edge case in my opinion please be aware that this feature will one be available on browser which natively supports it (https://caniuse.com/#feat=mdn-css_properties_width_max-content) and I'll not polyfilling it on other browsers. (There also aren't any polyfills as far as I know) - In this case also the `intrinsic` value will be supported on older safari versions.

**Comment by KingSora** [comment]
This is now implemented in [v1.12.0](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.12.0) Thanks!
