### ISSUE TITLE
Can't get OverlayScrollbars to work on dynamic page

### ISSUE THREAD

**Issue by GnussonNet** [KingSora/OverlayScrollbars#207]
**Describe the bug**
When I dynamically load a div called "validator-container" with a "textarea" with id "HtmlValidator" inside a div called "dynamic" I do not get any scrollbar. Also I do not get the custom textarea. When I add "os-host-flexbox" to the dynamic div I do not get the native scrollbar but still I do not get any OverlayScrollbar.

**To Reproduce**
Here is my code:
```
$(function () {
  $(".content").overlayScrollbars({
    updateOnLoad: ["div"],
    className: "os-theme-dark",
  });

  $("#HtmlValidator").overlayScrollbars({
    className: "os-theme-light textarea_wrapper",
    updateOnLoad: ["div"],
    textarea: {
      dynWidth: true,
      dynHeight: false,
    },
  });
});

// My HTML:
<div class="dynamic os-host-flexbox">

</div>

// And the dynamically HTML that loads into "dynamic":
<div class="validator-container">
  <textarea id="HtmlValidator" wrap="off"></textarea>
  <button onclick="htmlValidate()" id="HtmlValidatorBtn">Validate</button>
</div>

```

**Environment**
I use electron to build this but it do not work on my regular HTML files ether.

**Comment by KingSora** [comment]
Good day!

Before solving your issue, I want to hint that this option:
```js
updateOnLoad: ["div"]
```
doesn't make sense, since a `div` element doesn't emit a `load` event. Please delete this option, as it is intended for advanced / special use cases where you need to adjust the performance of the plugin according to the media elements your content has. In your case the plugin just runs unnecessary code.

Now to your issue, I assume this is happening because you initialize the plugin on a element which isn't loaded at the time you're initializing the plugin. You have to be careful that the element to which you're initializing the plugin also is in the DOM at this point in time. If you could somehow create a demo for me, I could create example code for you.

**Comment by KingSora** [comment]
Any news here @GnussonNet?

**Comment by KingSora** [comment]
I'll close this issue because of inactivity, please don't hesitate to reopen it in case it gets relevant again.
