### ISSUE TITLE
The width of .os-content-glue is one pixel smaller than that of .os-host

### ISSUE THREAD

**Issue by wuyuweixin** [KingSora/OverlayScrollbars#212]
The width of .os-content-glue is one pixel smaller than that of .os-host

**Comment by KingSora** [comment]
Good day!

Ok, thanks.. but could you give me more information about this? A demo would be very helpful for example. Please also describe to which unexpected behavior this leads because sometimes this pixel difference is [intentional](https://github.com/KingSora/OverlayScrollbars/blob/35fdfefe5e32c32a05f484dd724a871d00e27354/js/OverlayScrollbars.js#L3679-L3688).

**Comment by wuyuweixin** [comment]
@KingSora repo: [https://github.com/wuyuweixin/overlayscrollbars-vue.git](url)

**Comment by wuyuweixin** [comment]
[Intentional](https://github.com/KingSora/OverlayScrollbars/blob/35fdfefe5e32c32a05f484dd724a871d00e27354/js/OverlayScrollbars.js#L3679-L3688),Got it !
