### ISSUE TITLE
Unexpected clickScrolling behavior with round themes

### ISSUE THREAD

**Issue by opolskitom** [KingSora/OverlayScrollbars#238]
![slider](https://user-images.githubusercontent.com/48275516/87255935-eff3f780-c45c-11ea-80bb-115b5f3c6814.gif)
The handle seems to overshoot and never land centered with the cursor when click scrolling with the round themes. Would love to use this theme, however, would also like to click scroll properly. This can be visualized on your [demo styling page](https://kingsora.github.io/OverlayScrollbars/#!demos/styling).

 - Windows
 - Google Chrome (Version 83.0.4103.116 (Official Build) (64-bit))

**Comment by KingSora** [comment]
Good day!

This funcationality was designed after the corresponding native browser functionality, which works like that:

> Scroll a fixed amount of pixels every x milliseconds as long as the mouse button is pressed, until the scroll offset passed the corresponding mouse position on the scrollbar track.

You can test this in Firefox or chrome, open a page with overflow and then click on the tack, you'll see, that the scroll position also wont stop exactly where the cursor is. This approach gets less and less noticeable the larger the overflow is.

So it was never intended that the scroll is stopping exactly where the mouse is, it is just stopping somewhere near it. In this example it just looks like the scroll is missing the mouse by a large amount of pixels because of the small scrollbar handle and the short overflow. In reality it wouldn't be as noticeable. You can always release the mouse button to stop the scrolling on the correct place though. You can also press `shift` while clicking to scroll instantly to the point you want.

**Comment by opolskitom** [comment]
Thank you for the information! 
Could the following be a result of user error or is there a way to make it more accurate to the native functionality? I actually asked about this because I tried it originally on a medium scale, and it seems to be pretty apparent. My page has a variable overflow depending on the selection of elements so it may be smaller or larger depending on the user. I do see that it is indeed functional on much larger overflows however!
![slider2](https://user-images.githubusercontent.com/48275516/87276147-b8fa0200-c4ad-11ea-8e8c-e407bd1cf9a6.gif)

**Comment by KingSora** [comment]
I can change the amount of pixels which are scrolled. Currently its exactly the size of the viewport of the host element: https://github.com/KingSora/OverlayScrollbars/blob/master/js/OverlayScrollbars.js#L4641

But this value wasn't choosed randomly, normally the size of the scrollbar handle corresponds to the viewport size of the host element, thats why it isn't so apparent with a normal sized scrollbar handle. I'm honestly not sure how I can improve this situation other than to make it also somewhat dependent on the handle size.. but then again I don't know whether thats the correct way. I have to think about it.

**Comment by opolskitom** [comment]
I understand, thank you for the consideration. 
Love the plugin btw, definitely the best of its kind.

**Comment by KingSora** [comment]
@opolskitom I'm happy to tell you that I found a suitable solution for this problem and it will definitely be implemented in the next version!

**Comment by KingSora** [comment]
Implemented in [v1.13.0](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.13.0).

**Comment by opolskitom** [comment]
Really great stuff!!!!!! Thank you!
