### ISSUE TITLE
Scrollbar initially hidden with autoHide=leave if mouse over component on mount

### ISSUE THREAD

**Issue by mallison** [KingSora/OverlayScrollbars#239]
**Describe the bug**
When using `autoHide: leave`, if the mouse is over the scrollable content when `OverlayScrollbarsComponent` mounts the scrollbars remain hidden and do not show on scroll.

**To Reproduce**
1. Load a page using `OverlayScrollbarsComponent` with the mouse over the scrollable content
2. Scrollbars are not initially visible and remain hidden if you scroll

**Expected behavior**
The scrollbars should be initially visible if the mouse is over the scrollable content when `OverlayScrollbarsComponent` mounts.

**Examples**
https://codesandbox.io/s/nervous-lovelace-qb7f5?file=/src/App.js

**Environment**
 - Used Operating System(s): MacOS 10.14.6
 - Used Browser(s) (with version): Chrome 83.0.4103.116 Safari 13.1.1 Firefox 78.0.1

**Additional context**
N/A

**Comment by KingSora** [comment]
Good day! 

Thanks for the report, this is related to #48 where the user had the same issue. I thought I fixed it already.. turns out it's only fixed on Firefox and the fix doesn't work inside chrome because the desired event doesn't gets triggered.

I guess I have to investigate further into this, but as of right now I don't really have a plan how to fix it in a elegant way.

**Comment by mallison** [comment]
Hi @KingSora !

Thanks for looking at this so quickly (and for the work you've put in to this library!)

For now I'm working around by manually firing a `mouseenter` event if the mouse is over the content. I don't know either if there's a more elegant solution.

**Comment by KingSora** [comment]
@mallison this might work if the mouse is over the element, but in this case the scrollbar will also be visible if the mouse isn't over it, or am I wrong?

**Comment by mallison** [comment]
Yeah, I'm an idiot. I don't know how to get the initial mouse position or tell if an element is hovered on load. The library I'm switching from, perfect-scrollbars, does it somehow so I'm having a look to see how.

**Comment by mallison** [comment]
Urgh, I'm wrong again! perfect-scrollbar doesn't show either but it does reliably show on scroll or mousemove.

**Comment by KingSora** [comment]
On scroll or mousemove `OverlayScrollbars` also has the `autoHide: move` option.

**Comment by mallison** [comment]
To replicate current behaviour what I'd need is a combination of `move` and `leave` -- so the scrollbar stays on while over the content. However, now I've played around with `move` it might be nicer than having scrollbars always on (and matches how scrollbars typically work on mobile) 🤔.

Thanks!

**Comment by KingSora** [comment]
@mallison The `move` option was added later into the plugin because users just expect this behavior. Generally speaking there is no combination of `move` and `leave`. 

`move` will hide the scrollbars after the scroll position changed, or after you've moved the mouse.
`leave` will hide the scrollbars after you've leaved the host container with the mouse.

Both options look similar, but they are in fact very different (at least implementation wise) because `move` trys to hide the scrollbars bascially after any interaction and `leave` only when the mouse left the host container. So `move` is basically a more aggressive version of `leave` so to speak.

**Comment by mallison** [comment]
I'm happy to go with `move` -- it actually works better than the previous behaviour I was trying to replicate.

I'd be keen to see if you figure out the initial render problem. I experimented quickly with `:hover` and `mouseenter` but nothing seems to trigger until the mouse is moved. As you say, there must be a way!

Thanks for the help.

**Comment by KingSora** [comment]
Unfortunately I'm not able to figure out a suitable fix for chrome. Chrome won't fire any event when a element is rendered and if I would do it with something like a `MutationObserver` I'm not able to get the mouse position. The fix (if any exists) would be very complex - too complex to justify its benefit. 

I'm sorry but I can't fix this issue on chrome as long as the browser won't provide any mouseevents on rendered elements.
