### ISSUE TITLE
Scrolling under fixed element

### ISSUE THREAD

**Issue by ekr3peeK** [KingSora/OverlayScrollbars#249]
**Describe the bug**
Overlay Scrollbar does not register scroll when it is overlaped by a fixed element.

**To Reproduce**
1. Visit [this fiddle](https://jsfiddle.net/qabp2wfo/)
2. Inspect the fiddle with the javascript line commented out
3. Try scrolling over the red box, the scrolling should occur
4. Uncomment javascript code in fiddle to initialize OverlayScrollbars
5. Try scrolling over the red box, you can't

**Expected behavior**
I would expect that OverlayScrollbars should mimic how the browser natively implements this type of scenario, ie, to allow the scrolling underneath the fixed element.

**Environment**
 - Used Browser(s) (with version): Tested in `Firefox 78.0.2` and `Chrome 84.0.4147.89`

**Comment by KingSora** [comment]
Good day!

Currently this behavior isn't possible to fix because generally fixed elements are blocking the scrolling events to propagate to the element below. The only exception there is the `body` element. Unfortunately `Overlayscrollbars` is replacing the `body` element as the scrolling element, so thats why this behavior is present in the first place.

Maybe I can adress it in `v2.0.0` but until then it's not possible to improve it I'm afraid.

**Comment by ekr3peeK** [comment]
I've managed to solve this with the following css in the meantime: `pointer-events: none` on the fixed element. For those who do not need to register events on the fixed element this may also work. If you indeed need to listen to events from the fixed elements also, you can write a small javascript that will simulate this.

**Comment by hallaji** [comment]
> I've managed to solve this with the following css in the meantime: `pointer-events: none` on the fixed element. For those who do not need to register events on the fixed element this may also work. If you indeed need to listen to events from the fixed elements also, you can write a small javascript that will simulate this.

Well, I would not prefer to disable `pointer-events` as it's a nav bar in my case.

**Comment by agusterodin** [comment]
This is a showstopper since even if you disable pointer events on a navbar for example and set all direct children to pointer-events: all, scrolling is still blocked when scrolling from overtop of those child elements.

**Comment by KingSora** [comment]
@agusterodin for `v1.x` this won't change I'm afraid.. In `v2.x` this shouldn't be a problem anymore.

**Comment by ekr3peeK** [comment]
@KingSora do we have an ETA for `v2.x`?

**Comment by agusterodin** [comment]
> @KingSora do we have an ETA for `v2.x`?

If this is a showstopper for you as well, you can achieve a very similar effect to fixed with position:sticky. Allows me to have a navbar fixed at the top without broken keyboard navigation. 

The only real drawback to this versus using fixed is that browser's  built-in scroll position determination functionality when tabbing between focusable item treats the sticky element as if you can see through it. This means that the item you tabbed to could potentially be partially covered up by the sticky element. This is most obvious by if you set your navbar with a crazy big height and tab and reverse tab (shift + tab) between links.

Not as big of a deal as broken scrolling under fixed element so i'll write my solution off as a win for now. Looking forward to 2.x when I can switch these stickys back to fixed and fix this minor issue :D

Hope this helped you.

**Comment by KingSora** [comment]
@ekr3peeK theres no ETA currently, but I'm working actively on it. (you can checkout the `v2.0.0` branch if you're interested)
But it will certainly take some time, as I'm creating lots of tests to make the quality of `v2.0.0` event better.

**Comment by ekr3peeK** [comment]
> 
> 
> > @KingSora do we have an ETA for `v2.x`?
> 
> If this is a showstopper for you as well you can....

I've managed to solve my problems with a rather complicated piece of javascript code, which on mouse scroll removes the pointer events from the fixed element, and on mouse scroll end adds it back. It is VERY hacky, but until `v2.0.0` it will do it's job:)

**Comment by KingSora** [comment]
`v2` released today which hopefully improves on this behavior :)
