### ISSUE TITLE
Hides back to top button after adding it in

### ISSUE THREAD

**Issue by watatomo** [KingSora/OverlayScrollbars#258]
Hello! For some reason, the scrollbar hides the back to top button upon adding it in. An example can be seen [here](https://watatomo.github.io/tl/overlayscrollbar/). The page without the scrollbar is [here](https://watatomo.github.io/tl/).

Unrelated to this, but it would also be nice if the scrollbar is disabled on mobile (but I'm sure there's an easy way to this).

Any help would be greatly appreciated!

**Comment by KingSora** [comment]
Good day!

The back to top button isn't appearing, because currently it's programmed to listen to the scroll offset of the window element, and if this scroll offset is higher than 0, the button appears. Unfortunately `OverlayScrollbars` changes this behavior, because it wraps around its items, so the scroll offset of the window is 0 all the time (because the OverlayScrollbars elements are handling the scrolling, not the window element).

You can set use the option `nativeScrollbarsOverlaid: { initialize: false }` to not initialize the plugin for all browsers which already have overlaid scrollbars (like mobile browsers).

**Comment by watatomo** [comment]
Ah, yeah. I can see that now. It doesn't look like there's much I can do about that as the percentage relies on calculating the window height. Thanks for pointing it out, though! ~~Unfortunate how the default scrollbar for anything other than Apple isn't overlaid, honestly.~~

**Comment by KingSora** [comment]
@watatomo If you can change how the percentage is calculated, you can do soemthing about it though..
