### ISSUE TITLE
How would I impleten the 4th example from the Demo?

### ISSUE THREAD

**Issue by itshallrun** [KingSora/OverlayScrollbars#262]
I woul like to add almost the same gradien from the demo example 4.
![image](https://user-images.githubusercontent.com/21173275/92480530-4f644e80-f1e5-11ea-855f-32c4f6a60d29.png)
And some arrows in the center of the gradient.

How can i achieve this with react?
Is this example somewhere on github?

I am not sure if I should use the extensions for this, or if there is a better way?

**Comment by KingSora** [comment]
Good day!
The source code for the whole page is here on github. This section in particular can be found here: https://github.com/KingSora/KingSora.github.io/blob/master/OverlayScrollbars/js/demos.js#L1377-L1425

If you need a React example, please let me know. I'll try to create one as soon as I have time for it.

**Comment by itshallrun** [comment]
Hello @KingSora,

thank you very much for the quick response.
I tried to set up a quick React example myself, but I got stuck.
Somehow the ratio never hits the extreme value (0 or 1), which I need to toggle the gradients.
What am I doing wrong?

[codesandbox example](https://codesandbox.io/s/demo-cfv2i)

![demo](https://user-images.githubusercontent.com/21173275/92656069-b6235e00-f2f2-11ea-84b1-d37c5d911e82.gif)

**Comment by KingSora** [comment]
@itshallrun This is a perfect example of how `react` is implementing events. Because they are [doing their own thing](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation) and `OverlayScrollbars` is using `addEventListener` on the `viewport` element, there is a small mismatch in timing. This leads to the issue that the cache inside the plugin isn't updated yet, thats why you are getting the values of the previous iteration instead of the current.

To fix this, use the `onScroll` callback in the options: https://codesandbox.io/s/demo-forked-f89xh

**Comment by itshallrun** [comment]
Thank you!
