### ISSUE TITLE
Use with table

### ISSUE THREAD

**Issue by BenjaminHorn** [KingSora/OverlayScrollbars#27]
Is it possible to use this plugin with a table?
I try to have a scroll-able tbody with a fix height, while the <th> behaves as a sticky header.

https://jsfiddle.net/Lnrk66e2/4/

**Comment by KingSora** [comment]
Good day!

I'm afraid, but this isn't that simple, since the HTML table structure doesn't allow any divs inside of a `<table>` element.

Nevertheless there are good and simple solutions. The simplest solution would be to use a plugin which will take care of your header. I've found [floatThead](https://github.com/mkoryak/floatThead). Unfortunately it's a jquery plugin, but there should be also jQuery independent solutions. 

I've created a small demo for you: [https://jsfiddle.net/Lnrk66e2/5/](https://jsfiddle.net/Lnrk66e2/5/)

If I have a bit more time I'll try to work out a better solution without the need of a plugin, but until then this would be my recommendation.

**Comment by BenjaminHorn** [comment]
@KingSora thank you for the jsfiddle!

**Comment by KingSora** [comment]
Since your question is answered I'll close this issue for now.
I've added it to my todo list: https://github.com/KingSora/OverlayScrollbars/issues/39

In the future I'll implement a `extension system` and I'll write a extension which takes care of this problem.

**Comment by adsee42** [comment]
@KingSora 
Sorry for commenting in a closed issue.

From #39 , the `extension system` seems to be implemented.
Any update on using with `table`?

**Comment by KingSora** [comment]
@adsee42 well, no.. 

With the extension system you would be able to make it easy to use the plugin with a table, but you have to write this extension yourself, based on your expectations / features needed.

**Comment by MylesWardell** [comment]
Just for clarification their is no method of initializing the scrollbars outside the table but defining the tbody as the height in which to listen to scroll updates? 


Not correct syntax but demonstrates what I think is potentially possible? 
```
<table>
	<thead/>
	<tbody initialize-scrollbar ref={ref} />
</table>
<scroll x>
```

currently we have the scrollbar wrapping the entire div but just want the scrollbar to stop before it hits the header rather than go through it
