### ISSUE TITLE
Touch support works even i disabled it

### ISSUE THREAD

**Issue by NazarBroslavskyiEpam** [KingSora/OverlayScrollbars#280]
**Describe the bug**

when I turn off the touch support,  it still works

**To Reproduce**
1. Go to https://kingsora.github.io/OverlayScrollbars/#!demos/basic
.
2. set on `touchSupport: false` in scrollbars option.

3. Turn on mobile view and you will see that scrollbar reacts to the touch event

**Expected behavior**

The scrollbar should not react to touch events.

![image](https://user-images.githubusercontent.com/71328797/99914261-c13c3680-2d04-11eb-90d8-ddd751ec7c76.png)

**Comment by KingSora** [comment]
Good day!

I tried it out briefly and couldn't reproduce it. Are you sure that the actual _scrollbars_ are reacting to touch events and not just the viewport?

**Comment by NazarBroslavskyiEpam** [comment]
sorry. Maybe I misunderstand you. I think when I disable touchSupport it will not be work, but it works. Actually, i only need to disable touch events. 
![image](https://user-images.githubusercontent.com/71328797/99915127-6ad1f680-2d0a-11eb-8864-5f045deec23e.png)
see i can move scrollbar

**Comment by KingSora** [comment]
The touch support relates only to the scrollbar itself, not to the viewport. If you disable touch support, you're still able to scroll by swiping the viewport, but the scrollbar themself doesn't do anything (because in mobile environment you often just wan't scrollbars as indicators which doesn't react to any events):

![grafik](https://user-images.githubusercontent.com/12936317/99916098-52f97300-2d08-11eb-8f79-db40530f1cc2.png)

In case it doesn't behave like that on your side, please post details about your operating system and browser (with version numbers).

**Comment by NazarBroslavskyiEpam** [comment]
Yes. I agree with you. It works as you describe. It is my fault.  Your scrollbar the best I have found ever. I would like to ask you How can I disable touch support to the viewport also in the angular project. Thank you.

**Comment by KingSora** [comment]
Well, the plugin doesn't offer such a functionality.

However you can use disable with this code snippet:
```js
var viewport = osInstance.getElements().viewport;
vewport.addEventListener('touchstart', function(e) { 
  e.preventDefault(); 
});
```
In this way all touchevents are consumed and prevented. Thats one possible solution I guess, although it is (in my opinion) really ugly.

**Comment by NazarBroslavskyiEpam** [comment]
Thank you very much. I have been struggling with this too long today. I  appreciate it very much. I am closing the issue.
