### ISSUE TITLE
will-change in os-viewport

### ISSUE THREAD

**Issue by fernandodelgadomtech** [KingSora/OverlayScrollbars#283]
I noticed a boost in the scroll performance when I add this property to the os-viewport class, but itt also messes up the scrollbar tracking.

Would it be possible to add this css property to the os-viewport?

**Comment by KingSora** [comment]
Good day @fernandodelgadomtech!

What do you mean with "it messes up the scrollbar tracking"?
There is a reason why I wouldn't like this prop by default: thats because this prop is pretty dependent on the usecase of how you use the component. If you use it on a big area it probably can make sense, but if its somewhere else it could doe more harm. So I believe its the best to let the user decide when to add it instead of addind it by default everywhere.

**Comment by fernandodelgadomtech** [comment]
After some testing I was able to identify the scrollbar tracking was an issue from my end.

I have a question based on your comment... when is the best time to add such property, only for big areas or do you consider something holding a lot elements could be a good case too?

**Comment by KingSora** [comment]
I guess I would only use it, if I have some noticable performance issues. I only mentioned `big areas` because its more likely then that users interact with it. On [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change) they are writing:

> Important: `will-change` is intended to be used as a last resort, in order to try to deal with existing performance problems. It should not be used to anticipate performance problems.
