### ISSUE TITLE
Remember scroll position after reload or page switch

### ISSUE THREAD

**Issue by travico** [KingSora/OverlayScrollbars#29]
We use the  OverlayScrollbars  on a body element which works great.

The only problem is when the user scrolls down the page and reloads the page the scrollbar always gets initialized to top most position. That means with other words, he does not get back to the former position on the page.

The standard scrollbar seems to consider that. We initialize OverlayScrollbars  in the document.ready() function. Do we oversee something? Or is it not possible to "remember" the position of the scrollbar?

Many thanks for a feedback.

**Comment by KingSora** [comment]
Good day!
It's indeed possible to remember the position, but you have to do it yourself. 

The browser offers a solution for this cases, its called `sessionStorage` or `localStorage`. This objects are able to save information which will be available even if you switch or reload your current site. 

Please note that `sessionStorage` will be cleared after you close your window (the whole browser window, not the tab) and `localStorage` will never be cleared unless you (or the user) clear it manually. Unfortunately you can only save strings in these storages, but this shouldn't be problem since you can save objects as a `JSON` string. `sessionStorage` and `localStorage` have high browser support as you can see [here](https://developer.mozilla.org/de/docs/Web/API/Window/sessionStorage).

I think its better to save this information in `sessionStorage`. 
I've written a small demo for you: https://jsfiddle.net/7pn7nsk6/

I hope I could fix your problem.

**Comment by KingSora** [comment]
I'm glad I could help you! Thanks for providing the complete solution here, so others can also benefit from it.
If you have other questions or if you find any bugs, please don't hesitate to open a issue.
