### ISSUE TITLE
How do I get the scroll position?

### ISSUE THREAD

**Issue by chrisredbutton** [KingSora/OverlayScrollbars#3]
I can't seem to get the scroll position of the element.
I've tried it like this:
pageContentScroll);`

Maybe I'm overlooking something or misunderstanding your documentation, but it's not working for me. Could you please help me get this right?

**Comment by KingSora** [comment]
I know you've already closed this issue, but due to documentation purposes I'll answer it.
You can track the scrollposition like this:

`
var instance = $(elem).overlayScrollbars({ }).overlayScrollbars();
instance.scroll().x.position //scrollLeft Position in px
instance.scroll().y.position //scrollTop Position in px
`

It can be also found in the documentation: [scroll-method](https://kingsora.github.io/OverlayScrollbars/#!documentation/method-scroll)
