### ISSUE TITLE
A shift of scrollbar during page load

### ISSUE THREAD

**Issue by 01Kuzma** [KingSora/OverlayScrollbars#349]
Hi!
Thank you for a great plugin!
I have a small problem, while the page is loading there is a small shift near the scrollbar.
Is it a bug or there are specific options to get rid of it?
I'm attaching a short video.
I'm using the `jQuery 1.13` version and load it within a Gantry 5 Framework for Grav CMS.
The init code comes before `</body>`:

```
$(function() {	
	$("body").overlayScrollbars({
className: "os-theme-light custom-scroll",
        });
});
```

Main CSS is loaded in body tag:
`<link href="...OverlayScrollbars.min.css" type="text/css" rel="stylesheet">`

Any thoughts?
Thank you!

https://user-images.githubusercontent.com/569504/119267134-0d096300-bbf6-11eb-9fb6-164f50030478.mp4

**Comment by KingSora** [comment]
Good day @01Kuzma!

The plugin needs some time to initialize, to me it seems that this shift is happening because the native scrollbar is visible for a short amount of time while the plugin initializes. You can try to set following styles:

```
html, body {
  overflow: hidden;
}
```

So that you won't see the scrollbar even if the plugin is loading.

**Comment by 01Kuzma** [comment]
Great, thank you!
