### ISSUE TITLE
.sleep() not working on iPhone (iOS)

### ISSUE THREAD

**Issue by Anam0927** [KingSora/OverlayScrollbars#359]
**Describe the bug**
When the sleep function is called to stop scroll on mobile, it works on Android but scrolling still happens on iOS.

**To Reproduce**
1. Add overlay scrollbars to body and make it sleep on some action
2. Test it on iPhone

**Expected behavior**
The scrolling should stop on iOS also just like how it stops on Android

**Environment**
 - Used Operating System(s): iOS
 - Used Browser(s) (with version): Safari, Chrome

**Additional context**
I'm using the react library btw...

**Comment by KingSora** [comment]
Good day @Anam0927!

What do you mean with "scrolling should stop"? The `sleep` function is here to stop the plugin from doing its updating logic, it has nothing to do with actual scrolling

**Comment by Anam0927** [comment]
Oh, I thought sleep stopped the scroll since it's written in the docs that it won't react to touch or mouse events

In any case, using sleep does stop the scroll on Android tho...

**Comment by KingSora** [comment]
In the documentation I'm relating to mouse or touch events of the `scrollbars`.. So if you try move a scrollbar handle, it won't work.. but since the plugin just hides the native scrollbars and keeps native functionality, scrolling will be always possible if `overflow` is present and the `overflowBehavior` option is set to `scroll`.

You can probably achieve what you want (user can't scroll anymore) by setting `overflowBehavior` to `hidden`.
