### ISSUE TITLE
jQuery vs Vanilla version?

### ISSUE THREAD

**Issue by jsieler** [KingSora/OverlayScrollbars#36]
I wonder which version is faster? Any measurements possible?

**Comment by KingSora** [comment]
Its hard to tell. The most significant differences could appear in the `scroll` method, since the animation system is completely self-written in the vanilla version. 

You could try to do a benchmark on https://jsfiddle.net/ and measure the time in which "n" instances are initialized, updated and destroyed. Do this for both versions and you can do a comparison after.

**Comment by KingSora** [comment]
I'll close this issue, but I've added it to my todo list: https://github.com/KingSora/OverlayScrollbars/issues/39
