### ISSUE TITLE
Does scroll() function work correctly?

### ISSUE THREAD

**Issue by AlexayEugine** [KingSora/OverlayScrollbars#37]
Hi.
I used your OverlayScrollbars jquery plugin to show customized scrollbar.
I want to scroll top or bottom window automatically when user click a button.
So I tired this.
```
var instance;
        $(function() {
            //The passed argument has to be at least a empty object or a object with your desired options
            instance = $('body').overlayScrollbars({
                callbacks: {
                    onScroll: function(eventArgs) { 
                        var scroll = eventArgs.srcElement.scrollTop;
                        if (scroll >= 1) {
                            $(".boxfit-navbar").addClass("fixed");
                        } else {
                            $(".boxfit-navbar").removeClass("fixed");
                        }                    
                    }
                }
             });

             $('#down-to-bottom-button').click(function() {
                 instance.scroll(0, 250);
             });
```
But it doesn't work.
What can I do now?

**Comment by KingSora** [comment]
Good day!

In the jQuery version you have to be careful, because I didn't wanted to break the jQuery chain with the initialization, you wont get the instance like this.

Your initialization code looks like:
```javascript
var instance = $('body').overlayScrollbars({ });
```
But this method doesn't returns the instance, it returns the selected jQuery element, so the jQuery chain wont break and secnarios like this are possible too:
```javascript
$('body').overlayScrollbars({ }).fadeIn();
```

This is how you can get the instance:
```javascript
var instance = $('body').overlayScrollbars({ }).overlayScrollbars();
```

I've created a small demo for you: https://jsfiddle.net/hscxL92q/

**Comment by AlexayEugine** [comment]
Thank you for your reply.
It is solved by your help.

Cheers.

Sent from Outlook<http://aka.ms/weboutlook>
________________________________
