### ISSUE TITLE
Select2 + OverlayScrollbars. Sometimes scroll doesn't work

### ISSUE THREAD

**Issue by Erinov** [KingSora/OverlayScrollbars#375]
*reproduce*
You need to scroll a little, then move the cursor a little. After that, the scroll wheel works only downward. And if you pull the carriage, then everything works fine.

https://jsfiddle.net/Erinov/yr5qhue4/

**Comment by KingSora** [comment]
Good day @Erinov 

It seems the problem here is that `Select2` is creating some custom `mousewheel` events which are preventing scrolling in some cases.

![grafik](https://user-images.githubusercontent.com/12936317/124091604-4f745a00-da56-11eb-9c51-4b7a0496f0ab.png)

You could try to disable them at the risk of loosing some functionality of that library. Unfortunately OverlayScrollbars `v1` offers no functionality to possibly fix that issue (this will come in `v2`).

**Comment by Erinov** [comment]
Thank you, @KingSora, for pointing me on the right path to solve this issue.

I don't need `mousewheel` events on `Select2`, and after `unbind` this, it works fine.
