### ISSUE TITLE
scroll()'s complete() callback invoked earlier then scroll finishes

### ISSUE THREAD

**Issue by yarostbaklajana** [KingSora/OverlayScrollbars#380]
**Description:**

When using like _baseElement.scroll(0, 50, undefined, () => {  // invoked earlier });

*I suppose the reason of it is `refreshScrollbarHandleOffset()` method which is called within scroll() implementation right before the `complete()` callback invocation without waiting. Within the `refreshScrollbarHandleOffset()` there is hardcoded transition duration 250ms for the css transition which is calling repaint consequently. *

**Note**
This may be potential problem for users which frameworks which are relied on the requestAnimationFrame mechanism. 

**Workaround**
use like this:

` _baseElement.scroll(0, 50, undefined, () => { setTimeout(() => { // now finished for sure }, 250) });` 

or promisified version:

`const scrollTo = (coords) => new Promise(resolve => {
    _baseElement.scroll(coords, 50, undefined, () => {
      setTimeout(resolve, 250);
  })
})

// in other function
await scrollTo({x: 0, y: 20});`

**Comment by KingSora** [comment]
Good day @yarostbaklajana 

Hmm I'm not quite sure if I'm understanding the problem.. since you defined a `50ms` duration, how do you know the `callback` completed earlier? Do you mind creating an minimal example on [JSFiddle](https://jsfiddle.net/), [CodeSandbox](https://codesandbox.io/) or [StackBlitz](https://stackblitz.com/) where you demonstrate the issue?
