### ISSUE TITLE
Unexpected behavior with `form` and `fieldset` elements

### ISSUE THREAD

**Issue by iolyd** [KingSora/OverlayScrollbars#417]
**Describe the bug**
Applying OverlayScrolls to a `form` element containing `fieldset`s transfers the scroll handling to the children `fieldset` elements, as in it creates unwarranted instances for each `fieldset` rather than for the container `form`.
Is this expected due to some particular handling of forms by vendors?

**To Reproduce**
1. Create a `form` element
2. Append `fieldset` children
3. Create an instance of `OverlayScrollbars` specifying the `form` element as "host"
4. Inspect elements to see result

**Expected behavior**
The concerned `form` element should give the same result as obtained when using a div (or any other properly working tags, considering it is styled with `display: block`)

**Examples**
Simple demo: https://codepen.io/emmbema/pen/oNogBRO (I hope this is not due to some overlook on my part)

**Environment**
 - Tested with firefox and chrome

**Comment by KingSora** [comment]
Good day @iolyd 

Sorry for the late reply.. I see the issue here. In `v2` this issue is fixed. Ive transferred your original code to jsfiddle and replaced `v1` with `v2`: https://jsfiddle.net/khnawv9t/

I consider this as a edge case for `v1` and thus won't be providing a fix for that version.

Sorry again for the late reply!
