### ISSUE TITLE
Capability of scrolling over a fixed element

### ISSUE THREAD

**Issue by findawayer** [KingSora/OverlayScrollbars#44]
I have a fixed footer that is hidden behind content wrapper and gets revealed when the scroll hits the bottom of the page. OverlayScrollbars is working nice in general, but mousewheel up over this fixed footer does not trigger scroll change.

This can also be tested on the demo page, mouse-scrolling over the fixed header does not move the content scroll, while native scroll would do so.

_Note. Not sure this is rather a feature request than an issue, please tell me if I am misaddressing._

**Comment by KingSora** [comment]
Good day!

This is a very unfortunate behavior, since it is special to the `<body>` element.
To show you the problem, I've created two fiddles. The first shows how the `body` element handles scrolling on fixed elements. The second one shows how any other elements handles scrolling on fixed elements:

**body**: https://jsfiddle.net/mLq14ym9/1/
**any other**: https://jsfiddle.net/mLq14ym9/

If you try to scroll on the transparent red div, you will notice that scrolling is only possible if the overflowing element is the body element. If you are using a wrapper div like in the second fiddle this behavior isn't happening. 

Unfortunately OverlayScrollbars is wrapping its content, so the body element won't overflow.

I've figured out two workarounds to this problem though:
1. Use `pointer-events: none` directly on the fixed element and apply `pointer-events: all` only to elements where it is needed (such as links) like in this third demo: https://jsfiddle.net/mLq14ym9/2/
2. Use javascript to catch the `wheel` [event](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent) and simulate any scrolling: https://jsfiddle.net/mLq14ym9/3/ I've used jQuery and the [jquery-mousewheel](https://github.com/jquery/jquery-mousewheel) plugin in this demo, but only because make things simple, its also possible with plain javascript.

I highly recommend the first workaround since you still have native scrolling. Maybe there are more workaround but currently I can't figure out any other. Maybe you have any idea?

I also don't know if this behavior is somehow fixable since it depends on the browser and body element whether scrolling on fixed elements chains to the scrolling of their parent non fixed element.

**Comment by findawayer** [comment]
Interesting use of `pointer-events`, learnt something new by your reply. I can't come up with any plausible one by now, but will definitely continue pondering on it.

Thank you so much for the detailed answer and suggestions with explanatory demos. Love this.

**Comment by KingSora** [comment]
I'm glad I could help you! I'll close this issue for now, but if you find any other workarounds please let me know and document them here.

If you have any other questions or if you find any bugs, please don't hesitate to open a new issue!
