### ISSUE TITLE
Textarea sources

### ISSUE THREAD

**Issue by hxss** [KingSora/OverlayScrollbars#45]
Can you please provide textarea demo sources(html, css, js)?
https://kingsora.github.io/OverlayScrollbars/#!demos/textarea

Why in my simple test empty textarea have hight bigger than .os-host? How I can solve this problem?
https://codepen.io/hxss/pen/gzqEPg

**Comment by KingSora** [comment]
Good day!

This happens because you are specifying a textarea with `10 rows`. According to the [documentation](https://www.w3schools.com/tags/att_textarea_rows.asp) the rows property specifys the height of the textarea (not in pixels but in rows). Thats why the textarea is so big in your example, because it is at least 10 rows in height. If you remove this property, the height should be correct.

**Your example:** https://jsfiddle.net/qbpmc1ez/
**Corrected example:** https://jsfiddle.net/qbpmc1ez/1/

**Comment by hxss** [comment]
Thank you!

**Comment by KingSora** [comment]
I'm glad I could help you.

**Comment by PabloMarch** [comment]
Not sure if that was the intended behavior but when you set the height to be dynamic the scrollbars won't show so what is the intention of use the scrollbars when these never shows up? Is there a way to set the a max-height and when the textarea overflows this size the scrollbar appears? 

You posted an example of this here:
https://www.gitmemory.com/issue/KingSora/OverlayScrollbars/146/537849046

But one big problem is that the textarea nevers return to the original initial height.

Thanks
