### ISSUE TITLE
JSDOM + getComputedStyle

### ISSUE THREAD

**Issue by theo-staizen** [KingSora/OverlayScrollbars#456]
**Describe the bug**

A call to window.getComputedStyle branch breaks when using JSDOM.

https://github.com/KingSora/OverlayScrollbars/blob/6f40de9291e09819d339bef1599b4e3648dfa8c3/packages/overlayscrollbars/src/environment.ts#L82

(also at https://github.com/KingSora/OverlayScrollbars/blob/v1.x/js/OverlayScrollbars.js#L1779 for v1 branch)

According to jsdom, this error is thrown on purpose and the solution is to not pass the 2nd parameter (pseudo).
See https://github.com/jsdom/jsdom/pull/2918 and https://github.com/jsdom/jsdom/pull/3025 for more details

**Expected behaviour**

I understand that jsdom is not a real browser and as such I don't expect you to support it fully, but I am curious if perhaps there is another way to achieve the same result that doesn't require that function or the 2nd parameter.

As always, thanks for your help :)

**Comment by KingSora** [comment]
Good day @theo-staizen and thanks for reaching out..

The problem here is really that I need the second parameter and without it the function wouldn't do what it should. I fixed it for my jest setup like this: https://github.com/KingSora/OverlayScrollbars/blob/master/local/config/src/jest.setup.js I hope thats an acceptable solution for you

**Comment by theo-staizen** [comment]
Yeah, we ended up doing something similar on our side as well...
Oh well, it was worth a try. Maybe this issue will help someone else who runs into it.
Thx @KingSora and have a nice day
