### ISSUE TITLE
Scrollbar breaks when overflow property is applied to <html> tag

### ISSUE THREAD

**Issue by stepanjakl** [KingSora/OverlayScrollbars#477]
Firstly, congrats on releasing v.2 @KingSora, a great library!!

**Describe the bug**

I have a modal component on a site and when it is open the `<html>` tag is set `overflow: hidden` property in order to disable scrolling. However, after implementing your library, when overflow gets applied the whole page automatically scrolls to the top and the scrollbar stops working.

**To Reproduce**

You can simply test it on your [official site](https://kingsora.github.io/OverlayScrollbars/) with the Dev inspection tools and applying overflow style property to the `<html>` tag once you scrolled a bit from the top.

<img width="1005" alt="Screenshot 2022-11-16 at 23 39 24" src="https://user-images.githubusercontent.com/47005900/202319124-eac510a0-e23c-4f85-8d88-a0f91bcd2cd8.png">

**Environment**
- Used Operating System(s): macOS
- Used Browser(s) (with version): Chrome 107

**Comment by KingSora** [comment]
Good day @stepanjakl :)

I see... this comes from the fact that the browsers `viewport` is the `html` element. If it has no overflow, the page isn't scrolled, thats why the scrollbar isn't moving. What you scroll in this case is only the `body` element, which then counts as a separate container. You can verify this by trying to do `window.scrollTo(100, 100)` while the `html` element has the `overflow: hidden` style.

For now you have two options to work around this:
1. Set the `overflow.x` and `overflow.y` `option` to `'hidden'` instead of `'scroll'` and switch it back afterwards. (this is my recommended workaround)
2. Add a style which sets `overflow: hidden` on both, the `html` and `body` element. Something like:
```css
html.overflow-hidden,
html.overflow-hidden > body {
  overflow: hidden !important;
}
```
The `important` is needed to overrule the plugins styles.

I'll take a look whether I can improve this behavior without adding too much code and without adding more complexity to the plugin.

**Comment by stepanjakl** [comment]
Hello @KingSora,

Thank you for the answer and detailed explanation. I definitely understand what's going on. I am using Alpine.js and its Focus plugin with `.noscroll` [modifier](https://alpinejs.dev/plugins/focus#noscroll), which automatically applies inline `overflow: hidden` property to the `<html>` tag when activated. So unfortunately, I don't have control over the styling.

When the OverlayScrollbars library isn't included on the site applying overflow property doesn't cause the jump. It would be really nice if there was some check baked into the core of the library to prevent it like you said.

**Comment by stepanjakl** [comment]
@KingSora That was quick and it's working well now! Thanks a lot :)

**Comment by KingSora** [comment]
Jsem rád, že to funguje :)

> Glad it works :)

**Comment by stepanjakl** [comment]
> Jsem rád, že to funguje :)
> 
> > Glad it works :)

Hahah, já také.
