### ISSUE TITLE
Failed to work with TanStack/virtual

### ISSUE THREAD

**Issue by B-l-u-e-b-e-r-r-y** [KingSora/OverlayScrollbars#499]
Hello everyone!
I'm using the library [TanStack/virtual](https://github.com/tanstack/virtual), but it seems to conflict with OverlayScrollbars needing to set a height for the scrollbar to appear.

Here is an example: [CodeSandbox](https://codesandbox.io/s/fancy-sun-fwtxjd?file=/src/App.js:800-844)

`<div ref={osRef} style={{ height: "95vh" }}>`
If the height is specified, the scrollbar appears.

`<div ref={osRef}>`
Without specifying height, the virtualizer works, but the scrollbar doesn't appear.

Could I show the scrollbar without setting the height?
Or have any ideas?
Thanks for your help.

**Comment by KingSora** [comment]
@B-l-u-e-b-e-r-r-y Good day :)

Since you are using the `useWindowVirtualizer` hook you have to also initialize OverlayScrollbars to the `window` (`body`) element. I've created a demo for your here: https://codesandbox.io/s/youthful-shockley-0c17lm?file=/src/App.js

In case you wanna use the `useVirtualizer` hook I've also made a demo for you: https://codesandbox.io/s/angry-chebyshev-bv8h3d?file=/src/App.js

**Comment by B-l-u-e-b-e-r-r-y** [comment]
@KingSora 
Wow! You’re a lifesaver!

**Comment by Victor-Varghese** [comment]
Hi @KingSora `useVirtualizer` code doesn't work properly. Rows are not virtualised.

**Comment by KingSora** [comment]
@andreamazzatxt @Victor-Varghese Sorry for the late reply - In the example I forgot to limit the size of the viewport div.. so the virtualizer measured the div which could expand endlessly thus is could load all of the items into it. Setting a `maxHeight: '100%'` on that div fixed the issue: https://codesandbox.io/s/bold-robinson-78t7nz?file=/src/App.js

**Comment by brunopmartins** [comment]
Can someone repost the useVirtualizer example? The link isnt working anymore. thank you

**Comment by KingSora** [comment]
Related: https://github.com/KingSora/OverlayScrollbars/issues/639
