### ISSUE TITLE
What is the point of corner evement?

### ISSUE THREAD

**Issue by jsieler** [KingSora/OverlayScrollbars#5]
I've noticed small thing, that following div "os-scrollbar-corner" is added on all elements like span, div, etc. What is the point of this one, when corner is probably only needed on textarea fields?

**Comment by KingSora** [comment]
Modern browsers supports the CSS property `resize`. This property can be added on all elements not only on textareas: https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_resize

The plugin provides the same functionality, even for old browsers.

**Comment by jsieler** [comment]
Then may be it's better to check if this property is set, before adding, and only then add this element?

**Comment by KingSora** [comment]
This would require some "big" changes, but I'll see what I can do.

**Comment by jsieler** [comment]
Would the Window.getComputedStyle() method provide some help?
https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

The only limitation is Internet Explorer > 9...

Interesting discussion about it here: https://stackoverflow.com/questions/2664045/how-to-get-an-html-elements-style-values-in-javascript

**Comment by KingSora** [comment]
Maybe there was some misunderstanding. The plugin provides the same functionality but it doesn't depends on the CSS `resize` property. It depends on the `resize` property in your options which you've passed to the plugin: https://kingsora.github.io/OverlayScrollbars/#!documentation/options

I've already checked how work it would be to implement it the you wish, and its actually not that hard. It will be probably implemented in the next version.

**Comment by KingSora** [comment]
During implementation I've figured out a important reason why the element must be always added to the DOM: styling. This element isn't just here for the resize purposes but also for styling purposes. 

Lets take the following example: https://jsfiddle.net/hz2kxsfu/
As you can see, the corner element connects both scrollbars and can be a active component of styling. 

I've designed the stylability a little bit after this: https://css-tricks.com/custom-scrollbars-in-webkit/ and as you can see, the corner element is here too.

I am afraid, I wont implement this behavior because of this reasons.

**Comment by jsieler** [comment]
No, it's okay. You gave good explanation and reason. Thanks! :)
