### ISSUE TITLE
Scrollbar position

### ISSUE THREAD

**Issue by IgorLesnevskiy** [KingSora/OverlayScrollbars#51]
Hello!
Can I somehow move the scrollbar from the right side to the left side? I think, I can do it with styles, but it would be very useful to have the option setting the scrollbar position. I haven't found any piece of information about this in the docs.

**Comment by KingSora** [comment]
Good day!

Yes you are right, you can do it with styles. - Maybe I should write a article about in in the docs.
In the development process of the plugin I've thought about the most efficient way to style the scrollbars. And well, the most efficient way is to style them in CSS. Thats why I've decided that everything can be styled in CSS - for example the handle max or min length and so on. The plugin will always adapt to the styles you have set. The only exception is the visibility aspect, e.g. auto-hiding and so on. Thats something I couldn't let in the users hands, since in requires a bit of insight.

In a very early version the options actually had such a option, but I figured out this isn't the way to go. Of course I could set the CSS -Properties of  `top; right; bottom; left;` in Javascript according to your setting-choice, but what if you want a small gap between the edge and the scrollbar (or something like that)? That whouldn't be possible in such a way, or it would require another setting possibility.

If you want I can write a small `extension` for you, which provides this additional functionality, but it would limit you in your design choices.

**Comment by IgorLesnevskiy** [comment]
Hello!
Thank you for your answer. I've got your point about that. Well, I think this is not a big deal for me to control the side with styles. I was confused, 'cause this is a little bit unusual for me to control this kind of option with styles, but I think you are right in this case.

`I can write a small extension for you`
There is no need for that, thank you for your help! I like the way which you are enhancing your plugin.

**Comment by KingSora** [comment]
No problem! Thank you for your kind words. - I'll do my best to enhance the plugin even further. :)

**Comment by KingSora** [comment]
Small update here: I've created a [FAQ](https://kingsora.github.io/OverlayScrollbars/#!faq) page where I answer this and many other questions. I've enhanced the [styling documentation](https://kingsora.github.io/OverlayScrollbars/#!documentation/styling) and provided examples of how to adjust the the scrollbar-length, scrollbar-position and handle-length.

**Comment by IgorLesnevskiy** [comment]
Thank you!
