### ISSUE TITLE
Low scrolling performance in Safari

### ISSUE THREAD

**Issue by NikSimonov** [KingSora/OverlayScrollbars#53]
I have issues with scrolling performance in Safari, using latest version without jquery. Can you give me any optimization advice?

**Comment by KingSora** [comment]
Yes, please answer me some questions first:

- On which element are you using the plugin and with which options are you initializing it?
- Which OS version and which Safari version are you using?
- On how many elements are you initializing the plugin?
- Can you perhaps provide the link to your page so I can check what might cause the issue?
- Is the scroll-performance in the [documentation page](https://kingsora.github.io/OverlayScrollbars/#!documentation/options) also "low"?

**Comment by NikSimonov** [comment]
- using it on body, options are { autoUpdate: true, sizeAutoCapable: false }
- OS 10.13.5, Safari 11.1.1
- works perfectly fine in Chrome and Firefox
- just the body
- sorry, but i can't, maybe I'll look into any specific elements, that can cause problems?
- performance is fine on the documentation page

**Comment by NikSimonov** [comment]
Okay, nevermind, figured it out. Page has many placeholder images with filter: brightness(0) contrast(0);

**Comment by KingSora** [comment]
Is there any particular reason why you've set the `autoUpdate` to `true`?
Please initialize the plugin with `autoUpdate : null` (thats the default value). This should increase the performance.

**Comment by NikSimonov** [comment]
https://github.com/KingSora/OverlayScrollbars/issues/23
It was your question "Does the option autoUpdate : true improve the performance?"
I thought, if you asked about it, so there is a way it can improve it, that's it.
Reverting to default. Thanks for helping out.

**Comment by KingSora** [comment]
Now I understand. 
Genereally `autoUpdate : null` will give you the best performance for your browser. Only in some very special cases (like many animations or very many elements) you want to use a `updateLoop` since the updates will happen on a frequent basis. - But even in this cases a performance gain isn't very likely, but nevertheless I wanted to mention this possibility in the previous issue.

I'm glad I could help you, if you have other questions or problems, please don't hesitate to open a issue!
