### ISSUE TITLE
How to apply background to annoying empty square in the corner?

### ISSUE THREAD

**Issue by szmarczak** [KingSora/OverlayScrollbars#541]
**Is your feature request related to a problem? Please describe.**

![image](https://github.com/KingSora/OverlayScrollbars/assets/36894700/b054367a-7511-4e42-b438-d95bad9f5d8e)

**Describe the solution you'd like**

```css
--os-corner-square-bg: rgb(30 30 30);
```

**Describe alternatives you've considered**

None yet.

**Additional context**

Minimal repro: https://stackblitz.com/edit/vitejs-vite-aknb3r?file=src%2FApp.svelte,src%2Fapp.css

**Comment by KingSora** [comment]
Good day @szmarczak :) 

The corner element was available in the `v.1` version of the plugin, but was removed in `v2` due to various reasons. I'm thinking of bringing it back in the form of a plugin. Until then you can follow this workaround: https://github.com/KingSora/OverlayScrollbars/issues/518#issuecomment-1515761173

**Comment by KingSora** [comment]
@szmarczak Since version `v2.4.2` plugins are now available and this issue can be solved with the plugin posted here: https://github.com/KingSora/OverlayScrollbars/issues/518#issuecomment-1771264156
