### ISSUE TITLE
y-scrollbar handle goes past track length

### ISSUE THREAD

**Issue by szmarczak** [KingSora/OverlayScrollbars#542]
**Describe the bug**

![image](https://github.com/KingSora/OverlayScrollbars/assets/36894700/67fb6438-9e47-4ba2-b422-cd5ac7d7e7a4)

**To Reproduce**

Use the example below and scroll all the way down.

**Expected behavior**

Should be inside the gray bar.

**Examples**

https://stackblitz.com/edit/vitejs-vite-gamrvo?file=src%2FApp.svelte

**Environment**

- Used Operating System(s): Windows 11
- Used Browser(s) (with version): Google Chrome 114.0.5735.199 (Official version) (64-bit) (cohort: Stable)

**Comment by KingSora** [comment]
Good day @szmarczak 

Nice catch - after some times of checking my math I've concluded that this is happening because I'm using rounded values provides by the browser with its `offsetHeight` and `offsetWidth` values. Switchting them with their corresponding `getBoundingClientRect()` counterparts gets rid of this problem.

This fix will be in the next release which should be published soon. I'll inform you once its out.

**Comment by KingSora** [comment]
@szmarczak I've published `overlayscrollbars` `v2.2.1` which should fix this issue! Here is the full changelog: https://github.com/KingSora/OverlayScrollbars/blob/master/packages/overlayscrollbars/CHANGELOG.md#221
