### ISSUE TITLE
Examples in documentation

### ISSUE THREAD

**Issue by ricardo-reis-1970** [KingSora/OverlayScrollbars#544]
As far as I could detect, there are examples for all 5 SPA frameworks / libraries supported. These examples look like fully develop independent projects.

**Why are these examples not in the documentation page?**

Why must I clone the repo, build each of these examples and open its `index.html` in order to see it? It does not make much sense that such a visual proposition should not have one of those things thyat are worth a thousand words: a picture.

**Comment by KingSora** [comment]
Good day @ricardo-reis-1970 

Thanks for that suggestion! In the past I was thinking about this as well, but came to the conclusion that pictures aren't really sufficient, because in the end you just see some kind of content with scrollbars attached to it. (Technically you see the same thing on the on the [website](https://kingsora.github.io/OverlayScrollbars/).

So I was thinking that developers would be more interested in real examples - thus the examples folder with all of its content. I even set up [github codespaces](https://docs.github.com/de/codespaces) so there isn't a need to clone the repo anymore. 

Do you think the examples would become more accessable if I would setup a `codesandbox` or a `stackblitz` example?

**Comment by ricardo-reis-1970** [comment]
Greetings, King!

I agree that devs would be more interested in real examples, and that's why I (a developer) cloned the repo and had the React one running, although I might have struggled a bit with dependencies and ended up editing `package.json` into this:
```json
  "dependencies": {
    "overlayscrollbars": "2.2.0",
    "overlayscrollbars-react": "0.5.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
```

What I meant originally was to have the examples **directly** in the repository web page https://kingsora.github.io/OverlayScrollbars/. FrontEnd is also inhabited by UI designers whom, in some cases, are non dev-technical and could feel a bit daunted by the task of cloning a repo and making it work.

This way, they could experience the scrolllbars directly. In its current state, the website has no scrollbars in display whatsoever.

## And why is this all worth it
Let me just transcribe the reaction of my designer when I told him about your scrollbars last Friday:
```
I LOVE THE OverlayScrollbars !!!!!
Beautiful !!!
```

(Please excuse the space before the exclamation marks. He is French.)

**Comment by KingSora** [comment]
@ricardo-reis-1970 I've finished porting all those examples to `SackBlitz` so they can be viewed and edited without the need to checkout the repo. I'll need some more time to update the READMEs and the website though.. 

I really appreciate your feedback and fully agree. - I'm also happy your designer likes it :)

**Comment by KingSora** [comment]
@ricardo-reis-1970 I've created the new [Examples Page](https://kingsora.github.io/OverlayScrollbars/examples) which lists now all available examples. This page is linked in every README in each package.

I hope this is sufficient - In case you have any feedback I would be happy to hear it! :)
