### ISSUE TITLE
Reduce core file size by splitting functionality in extentions

### ISSUE THREAD

**Issue by Windvis** [KingSora/OverlayScrollbars#55]
Hey! This library looks really solid! I'm definitely going to try this.

The file size concerns me though. I know you are aware of this and are trying to reduce where possible.

I was wondering if it would be technically possible to split off non-core functionality into extensions, to limit the size of the core library? Things like rtl support, old browser support, ...

The combined file size would be about the same size, but the developers can choose what to include.

Now, to be honest, I haven't looked at the code in detail (6k LOC files are intimidating) so I have no clue how intertwined these things are.

**Comment by KingSora** [comment]
Thanks for your kind words!

I think I'll begin my post with a bit of a explanation of the code.
The code is splitted into 3 major components, I call them `compatibility`, `framework` and `plugin`.
- **compatibility** : functions which are unifying native methods which are different or not present across all browsers.
- **framework** : the framework which is used for DOM manipulation / traversing (jQuery in the jQuery version and a self written on in the vanilla version)
- **plugin** : the actual plugin with all its functions and so on

Lets say I'll drop IE8 support. The size of the `compatibility` and `framework` components will decrease because I don't have to worry about all the old stuff. - This may decrease the size about `1 - 4KB`.

Now these two components are as small as possible so lets focus now on the `plugin` component.
Before we do this, lets talk about the current features / options. For me, all of the current options (except the `resize`-option) are core-options. But since the resize-option was easy I've decided to implement it.

Alright, the `plugin` component is capsuled into:
- **options** : There I handle everything about options and defaultOptions.
- **globals** : Information which is needed across all instances.
- **loop** : The auto update loop across all instances (fallback for old browsers).
- **instance** : The actual instance object of the plugin.

The **options** part is taking care about the options you set. Currently it's not possible to set invalid options, the plugin simply won't accept them and will write a warning in the console to inform you about it.
To make this possible I've implemented a template system, which is checking strings and types for their correctness. 
If I change this and simply make it possible to set invalid options the size will decrease about `1 - 4KB`.

The **globals** object collects all information about the capability of the browser. For example if `transforms`, `transition` or the CSS3 `calc` function is available. If we drop the browsersupport, we wouldn't have to collect as much information, since many thing are simply available in modern browsers. This would decrease the size about `0.5 - 2KB`.

If we drop browsersupport we could drop the whole **loop** thing, because modern browsers would support the needed APIs. This would decrease the size about `1 - 5KB`.

Lets talk now about the **instance**. This is definitely the biggest part the whole code. There you have obviously the whole functionality of a instance. This part of the code is also very intertwined, to reduce the size. If we drop browsersupport it wouldn't have any effect here, because we are using here functions of the `compatibility` and `framework` components.

As you can see, if we drop the browsersupport we could gain about `2 - 11KB` of space. If we also drop the whole options checking thing we could gain up to `15KB` of space. This is the best case secenario.

---

Lets talk about the idea of splitting functionality into extensions. I've thought about it too and I think this is a good idea. I would like to do it like [modernizr](https://modernizr.com/download?setclasses). You could download a plugin version which only includes the features you need. - Right now I don't really know how much work this would be, since its impossible to capsule every feature, but I think the amount of work would be very high.

If the plugin gains more attention and the community grows, it's possible I would create "special-versions" which only includes a special featureset, but currently I have other things which have a higher priority as this.

I hope I could help you with my answer and clear things up a bit

**Comment by MarcosRakesh** [comment]
Hello,

Removing old browser support will be great, the old browsers are no longer supported, even IE11 and most use Edge. There is a reason why you keep support for old browsers ? Remove or make other version because this is the only library with old browsers support.
So far is the best scrollbar library. Thank you

**Comment by KingSora** [comment]
@MarcosRakesh You are right. 
The reason why I've decided to support IE8 is, because as I started developement (2016), Windows7 was still a thing and I wanted to support as many browsers as possible. Since Windows7 support will end early 2020, I'll definitely do a second version of the plugin which will only support modern browsers. 
I don't know when this will happen though, but I have it on my backlog.

**Comment by NindroidX** [comment]
Thank you for the detailed explanation, and that is more than reasonable enough!

**Comment by KingSora** [comment]
@MarcosRakesh @NindroidX 
A small update here: I've briefly removed all the IE / old-browser stuff from the plugin code and reduced the size about `3KB`. Thats not much, indeed.

**Comment by MarcosRakesh** [comment]
@KingSora 
Hello,
Any ETA to remove unsupported browsers of IE, supporting only IE11 will be great because people need to start updating their browser, this is the only library with old browsers, if not can i have a version only with IE11 non-jquery?

**Comment by KingSora** [comment]
@MarcosRakesh Currently I've other things with higher priority to work on... There is no ETA, I'm sorry.
