### ISSUE TITLE
Element.ScrollIntoView()

### ISSUE THREAD

**Issue by shepelevstas** [KingSora/OverlayScrollbars#59]
Is it possible to make OverlayScrollbars to work with browser-built-in functions like `.ScrollIntoView()`? Or maybe I'm doing something wrong?

**Comment by shepelevstas** [comment]
Or can I do `instance.scroll($(selector), 1000);` to screen center?

**Comment by KingSora** [comment]
Good day! 

Please try the following:
```javascript
Instance.scroll({ el: $("#your-element"), block : "center"}, 1000);
```
For further information please check the FAQ page: https://kingsora.github.io/OverlayScrollbars/#!faq

I hope this solves your problem.

**Comment by shepelevstas** [comment]
Noticed some strange behavior of `.scroll({el:el, block:'center'})` if the _el_ is at the bottom. I've made a [codepen](https://codepen.io/shepelevstas/pen/pOjXmp?editors=1000) to experiment and can't get it to work. Could you have a look?

**Comment by KingSora** [comment]
I'm sorry, but I'm currently on vacation... 
I've checked your codepen with my phone, and I've noticed the problem. I'll be back on monday and will investigate as soon as I have some time left.

Thanks for pointing out this bug and for creating a suitable demo!

**Comment by KingSora** [comment]
Alright! I've checked it out, and it's indeed a bug. I'll fix this bug in the next version. Until then you can use a small workaround: simply call the `update` method _before_ you call the `scroll` method.

This bug is happening because the scroll method is using cached dimensions, and the update method is updating the cache.

**Comment by shepelevstas** [comment]
Thank you!=D

**Comment by shepelevstas** [comment]
I've got another one, but don't khow if it's a bug:
1. click and hold on the scroll bar
2. move pointer outside the window
3. release the left mouse button
4. move the pointer back into the window
and it's still draggin the scroll bar even without holding the mouse button

should it be like that, or is it a bug? should I create a new issue?

**Comment by KingSora** [comment]
Well.. I know what you mean, but this is hard (or impossible) to fix, because its only happening if you are using the plugin inisde a iFrame (codepen, jsFiddle and so on). If you try to trigger this bug on my [demo page](https://kingsora.github.io/OverlayScrollbars/#!overview), it won't happen, because I've took care of that. I'll investigate though!

**Comment by KingSora** [comment]
Small update on both bugs:

- The `scroll` method bug is already fixed. 
- I figured out the scrollbar-handle-iFrame-bug is only happening in chrome. Firefox is handling it correctly. I've found a suitable fix for this bug though.

**Comment by KingSora** [comment]
[Version 1.5.2](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.5.2) is out now and all mentioned bug are fixed! 
If you find any other bugs or if you have questions, please don't hesitate to open a issue.
