### ISSUE TITLE
Scrolling on position: fixed elements still not working

### ISSUE THREAD

**Issue by joshkalsi** [KingSora/OverlayScrollbars#593]
**Describe the bug**
Scrolling while the mouse is over an element with position: fixed doesn't scroll the page.

**To Reproduce**
Add a fixed element within an OverlayScrollbarsComponent - the fixed element blocks the scroll.

**Expected behavior**
The page should scroll properly.

**Examples**
Codesandbox: https://codesandbox.io/p/sandbox/overlayscrollbars-fixed-element-bug-7863qs

**Additional context**
I'm aware of issue https://github.com/KingSora/OverlayScrollbars/issues/249 - the resolution of that ticket was that the behaviour should be improved in version 2, however I'm on version 2.4.4 and still seeing the bug. Was this fixed and there's been a reversion in behaviour since that ticket, or did it only address certain circumstances?

**Comment by KingSora** [comment]
Good day @joshkalsi :)

The behavior in your example is normal browser behavior and is not related to the plugin... If you switch out the `OverlayScrollbarsComponent` with a simple `div` which has `overflow: auto` as style you'll get the same behavior. (https://codesandbox.io/p/sandbox/overlayscrollbars-fixed-element-bug-forked-glhnx9?file=%2Fsrc%2FApp.js%3A14%2C13)

The difference between your example and #249 is that in the other issue the fixed element is _not_ wrapped in a different overflowing container but its nearest overflowing container is the body element / the window scroller element.

If I change your example to the equivalent the native behavior is what you would expect. (https://codesandbox.io/p/sandbox/overlayscrollbars-fixed-element-bug-forked-27nc8l?file=%2Fsrc%2FApp.js%3A11%2C13)
If I then apply `OverlayScrollbars` to the body element it has the behavior you want and what was fixed in #249 (https://codesandbox.io/p/sandbox/overlayscrollbars-fixed-element-bug-forked-rpqy54?file=%2Fsrc%2FApp.js%3A13%2C11)

**Comment by KingSora** [comment]
@joshkalsi Youre welcome :)
