### ISSUE TITLE
Can't set defaults using jQuery

### ISSUE THREAD

**Issue by unexdesigns** [KingSora/OverlayScrollbars#6]
`OverlayScrollbars.defaultOptions({...})` and `$.fn.overlayScrollbars().defaultOptions({...})` throws an error, meaning you can't access `defaultOptions()` method.

Found a workaround though... But I'm not sure this is intended behavior.

```
$.fn.overlayScrollbars();
OverlayScrollbars.defaultOptions({...})
```

after calling `$.fn.overlayScrollbars()` everything works... Weird...

**Comment by KingSora** [comment]
Hello!

Yes you are right, this error indeed happens in v1.2.0. I am very sorry, but I've made a small mistake in the new implementation of this method. 

As you've figured out this bug happens only, if you're calling the `OverlayScrollbars.defaultOptions` method before you've called the `$.fn.overlayScrollbars` method. This seems weird but I can explain this behavior: All instances of the plugin shares a object, which holds global information. This object also holds the information for the defaultOptions since this information shall be the same across all instances.
This object is created the first time youre trying to initialize a instance (the initialization hasn't to be successful). Since you can initialize a instance with `$.fn.overlayScrollbars` the object gets created after this call and the `OverlayScrollbars.defaultOptions` method will work properly after that.

Please note that `$.fn.overlayScrollbars().defaultOptions` is invalid and doesn't exists. `OverlayScrollbars.defaultOptions` is the only way to set the Default Options.

I'll fix this bug later today and will release a patch with the version 1.2.1.
Thank you!

**Comment by KingSora** [comment]
The patch is out!
Please test it out and give some feedback so I can close the issue: https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.2.1
