### ISSUE TITLE
What is wrong with such a simple example using overlayscrollbars-ngx?

### ISSUE THREAD

**Issue by mlc-mlapis** [KingSora/OverlayScrollbars#600]
**Describe the bug:**

I tried a very simple example using the latest "overlayscrollbars-ngx" library. After checking all possible places and combinations, it's still unclear why the native scrollbar is showing while it shouldn't. It would be nice of you if you could help with this problem. Thanks a lot in advance.

**To reproduce:**

Please look at the example: https://stackblitz.com/edit/mlc-simple-overlayscrollbars

**Environment:**

- overlayscrollbars: 2.4.6
- overlayscrollbars-ngx: 0.5.1
- Angular: 17.0.8
- Used Operating System(s): Windows 10
- Used Browser(s): Chrome v120

**Comment by KingSora** [comment]
Good day @mlc-mlapis :)

I believe you just mixed up where the `.container` classname should be.. If you move it from the inner div to the `overlay-scrollbars` element everything is working. (https://stackblitz.com/edit/mlc-simple-overlayscrollbars-si7wuf?file=src%2Fmain.ts)

The problem was that if the `.container` classnames is applied to the inner div (which hasn't OverlayScrollbars applied) it will never overflow because of the `overflow: auto` style. Instead the element itself will hides the overflow and shows an scrollbar because its content is overflowing.

**Comment by mlc-mlapis** [comment]
@KingSora Have a lovely last day of this year!

You are right. I don't have any explanation for why I missed it. 😄 
Thank you a lot.

**Comment by KingSora** [comment]
Thanks! Have a lovely day as well! :)
