### ISSUE TITLE
Usage in Wordpress

### ISSUE THREAD

**Issue by ErnestPH** [KingSora/OverlayScrollbars#63]
Hi!

First of all, I would like to thank you for this plugin. This could be the solution to my problem. Unfortunately, I don't know how to implement this as I am not a a developer. So this is more of a request. I am sorry, I can't contact you anywhere else.

Anyway, my problem is only for Firefox and Chrome windows, it's showing the scrollbar, http://www.radioscristianas.com (white in color). Although there is a fix by disabling or using an add-on, it seems to be for individual users and not a solution globally. Upon reading this plugin, I am definitely sure that this can fix the issue.

My request, can you make a Wordpress plugin or a tutorial on how to add this on a server?

I hope I am following the rules and have not broken any. Thanks!

ErnestPH

**Comment by KingSora** [comment]
Good day!

Sorry for the late reply, I've been very busy the past days.

Since this is a Client-side-JavaScript-plugin, there isn't really a way to add on a server.
Basically you can implement the plugin on your wordpress page, like on any other page.
Just initialize it on the required elements after your page has been fully loaded and it should work.

I've tried to make a example for you, but there is a problem on your page. You are using a iFrame which hasn't the same origin as the webpage. Because of that you'll get a [peremission denied error](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy).

If you can change that, you could initialize the plugin like that:
```javascript
var iFrameBodyElement = jQuery("iframe[src=\"YOUR_IFRAME_URL\"]")[0].contentWindow.document.body;
var osInstance = jQuery(iFrameBodyElement ).overlayScrollbars({ });
```

**Comment by ErnestPH** [comment]
Hello Good day!

That is ok. Thank you for effort!

All the best for you
ErnestoPH
