### ISSUE TITLE
Prevent parent element scroll

### ISSUE THREAD

**Issue by hamed-ehtesham** [KingSora/OverlayScrollbars#65]
Hi Rene,

in past days i tested so many scrollbar plugins and this plugin is definitely the best,

does this plugin have option to prevent parent element scroll like this example [Codepen](https://codepen.io/LelandKwong/pen/edAmn) because i didn't find an option for it in options list

**Comment by KingSora** [comment]
Hi!

Well, no it doesn't. This feature is called `scroll-chaining` and it's currently enabled by default by any browser. Recently a new CSS rule was introduced which is able to disable `scroll-chaining`. It's called `overscroll-behavior` - [here](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior) is the documentation.

You can use this CSS rule like this:
```css
.your-element.os-host > .os-padding > .os-viewport {
  overscroll-behavior: none;
}
```

There are two reasons why I haven't implemented such a option until now: 
1. A Javascript solution would fix this problem only on `desktop` enviroment, because you are simply preventing the `wheel`-event and this doesn't include swipes on touch devices.
2. I think this option is a little bit too specific and should be handled by a extension,

If you wish I can write a small extension which takes care of that on desktop PCs, like in your example.

**Comment by hamed-ehtesham** [comment]
I created the [extension](https://www.npmjs.com/package/os-scroll-chain) and here is one example [Codepen](https://codepen.io/H4M3D3/pen/qJYjWq)

it exploits the CSS rule you mentioned and also `wheel` and `touch` events (so it does include swipes on touch devices)

**Comment by hamed-ehtesham** [comment]
Thank you for the info and surely the plugin again

**Comment by abdelhady** [comment]
I hope this extension gets its way in the extensions page (when page is ready) :+1:

**Comment by KingSora** [comment]
As the [Extensions page ](https://kingsora.github.io/OverlayScrollbars/#!extensions) is now ready (and I've decided how to list extensions), please add the topic `overlayscrollbars-extension` to your repo.

Your extension will be then listed on the Extensions page.

**Comment by hamed-ehtesham** [comment]
i did that

**Comment by KingSora** [comment]
Thanks - your extension is now listed!

**Comment by hamed-ehtesham** [comment]
No problem
