### ISSUE TITLE
Show card dropdown - list not showing overflown content

### ISSUE THREAD

**Issue by khullah** [KingSora/OverlayScrollbars#69]
I have a list with cards, which have a custom dropdown at the edge. I'm using overlayScrollbars to pretify the list's scrollbar, but the dropdown cannot overflow from that list anymore.

I've tryed to use all of overflowBehavior values, modify lib css classes, set `* {overflow-x: visible !important}`, fix widths, but nothing works. Any thoughts?

https://pasteboard.co/HL5XUf8u.png

**Comment by KingSora** [comment]
Good day!

Unfortunately I don't have enough info yet to give a suitable solution to your problem.
Please provide a reduced test case on [https://jsfiddle.net/](https://jsfiddle.net/) so I have a bit more insight.

**Comment by khullah** [comment]
Hello! thanks for the reply. Sorry for my late reply, took a while to isolate that piece of code from the rest of the app.

So, here it is: https://jsfiddle.net/Khullah/gxjah98v/20/

See how in the first list the 3-dotted button show the dropdown without a problem, but in the second list which has more itens and therefore the scrollbar, the same doesn't happen. For the horizontal axis, in the app there is a scrollbar for all lists, which I did not include but doesn't seems like is relevant here (you tell me).

thanks!

**Comment by KingSora** [comment]
Alright, I've took a look on that and your code was very muddled, so I've created a version which I could understand: [https://jsfiddle.net/gxjah98v/24/](https://jsfiddle.net/gxjah98v/24/). It's basically your example just without any JS initialized and the left / right column colored. I've also removed any additional styles which targets any of OverlayScrollbars elements.

As you can see, its not working as you expect, even if you don't initialize OverlayScrollbars. That means it's not a bug or something. The problem lies within your DOM. 

Your DOM current structure is like that:
```html
<div id="left">
  <ul class="collection kanban-list fundo-cinza-claro zindexCardFix">
    <li class="card horizontal hoverable" draggable="true">
      <div class="card-stacked">
        <div class="card-content hover-handle" unselectable="on" onselectstart="return false;">
          0
          <div class="fonte-cinza-claro">
            <i class="material-icons more right dropdown-button" data-activates="dropdownMore1">more_vert</i>
          </div>
        </div>
      </div>
      <ul id="dropdownMore1" class="dropdown-content more center-align">
        <!-- ...Dropdown content... -->
      </ul>
    </li>
  </ul>
</div>
```

The problem is, the element with the class `.kanban-list` has already the style `overflow: auto` which means everything inside will be clipped. You `dropdown-content` is no exception. The solution to this would be to move your `dropdown-content` into a div which wont't clip it. 

Unfortunately `materialize` wont let you do that, because it moves the `dropdown-content` right below its button automatically, no matter what you do.
We can solve that with javascript though:
```javascript
$('#left').append($('#dropdownMore1'));
$('#right').append($('#dropdownMore0'));
```

This would be it: [https://jsfiddle.net/gxjah98v/25/](https://jsfiddle.net/gxjah98v/25/). It works now with the native scrollbars. Time to initialize OverlayScrollbars:
```javascript
OverlayScrollbars($(".kanban-list"), {
  overflowBehavior: {
    x : "hidden",
    y : "scroll"
  }
});
```
And thats it: [https://jsfiddle.net/gxjah98v/26/](https://jsfiddle.net/gxjah98v/26/). Everything is working now. The issue lies within `materialize` and how it handles its dorpdown elements.

I hope I could solve your problem!

**Comment by khullah** [comment]
Terrific! Thanks for solving this, and sorry its not a bug. So my problem is deeper, 'cause the list is dinamically generated (so I copyed and modified the resulting HTML for the fiddle). Even more, the dropdown is copyed from wherever it is to next to the trigger button. Anyway, I can follow this new track thanks to you.

Sorry for the late response and thanks again, cheers

**Comment by KingSora** [comment]
I'm glad I could help you!
