### ISSUE TITLE
useOverlayScrollbars: Component Updates Cause removeChild Error

### ISSUE THREAD

**Issue by ssu2030** [KingSora/OverlayScrollbars#696]
**Describe the bug**

When using the useOverlayScrollbars hook in a React component, if the component containing the hook is updated without unmounting, a removeChild error occurs. This issue arises because the DOM elements managed by useOverlayScrollbars are not properly synchronized with React's virtual DOM. As a result, React attempts to manipulate DOM nodes that have not been fully unmounted, leading to the following error:

``` 
Uncaught Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
````

This behavior occurs in scenarios where React updates the parent or sibling components while the OverlayScrollbars-enhanced component remains in place.

**To Reproduce**

1. Use the useOverlayScrollbars hook to initialize a scrollable component.
2. Update the component without unmounting it (e.g., by changing props or triggering a parent re-render).
3. Observe the error in the browser console.

hooks.tsx

``` javascript
import { useOverlayScrollbars } from "overlayscrollbars-react";
import React, { useEffect, useState, useRef } from "react";

export function useCustomOverlayScrollbars() {
  
  const scrollBarRef = useRef<HTMLDivElement>(null);
  const parentContainerRef = useRef<HTMLDivElement>(null);

  const [initialize, scrollBarInstance] = useOverlayScrollbars({
    options: {
      scrollbars: {
        autoHide: "leave",
      },
    },
  });

  useEffect(() => {
    if (!scrollBarRef.current) return;

    initialize(scrollBarRef.current);
    const osInstance = scrollBarInstance();

    if (parentContainerRef.current && osInstance) {
      
      
      const dividerWidth = parentContainerRef.current.offsetWidth;
      const hostElement = osInstance.elements().host;
      hostElement.style.width = `${dividerWidth}px`;
    }

    return () => {
      if (osInstance) {
        osInstance.destroy();
      }
    };
  }, [initialize, scrollBarInstance]);

  return { scrollBarRef, parentContainerRef };
}
```

ErrorComponent.tsx

``` javascript
import React from "react";
useCustomOverlayScrollbars

function ErrorComponent({data}: props) {

  const {data} = props;
 
  const { scrollBarRef: ref, parentContainerRef: headerRef } = useCustomOverlayScrollbars();

    return (
      <div ref={headerRef}>
         <div ref={ref}>
            <button onClick={() => setContent("Updated Content")}>
              Update Content
            </button>
            <p>{content}</p>
          </div>
      </div>
    );
  }
```
When the data prop changes, the ErrorComponent re-renders, and during this update, an error occurs. Specifically, the error is related to the useCustomOverlayScrollbars hook managing the OverlayScrollbars instance. Since the DOM element referenced by ref is not unmounted correctly during the update, React's reconciliation process encounters a removeChild error. This issue arises because OverlayScrollbars directly manipulates the DOM outside of React's lifecycle, causing a desynchronization between React's virtual DOM and the actual DOM.

**Expected behavior**
The useOverlayScrollbars hook should handle component updates gracefully without throwing errors. DOM elements managed by the hook should be synchronized with React's virtual DOM during updates, ensuring proper cleanup and reinitialization if necessary.

Environment
Used Operating System(s):  macOS 15
Used Browser(s) (with version): Chrome 131.0.6778.109

Additional context
This issue highlights a fundamental mismatch between the lifecycle management of useOverlayScrollbars and React's virtual DOM. The error occurs because useOverlayScrollbars directly manipulates DOM elements, but React assumes full control over its virtual DOM tree. When React updates the component without unmounting it, the hook does not reinitialize or clean up properly, leading to inconsistencies.

A workaround is to use the OverlayScrollbarsComponent instead of useOverlayScrollbars, as it aligns better with React's lifecycle. However, this issue should be addressed to ensure compatibility with React's reconciliation process.

**Comment by ssu2030** [comment]
Currently, I am using the OverlayScrollbarsComponent React component, attaching a ref to it, and utilizing useEffect to access the instance internally and modify the host element's width.

**Comment by KingSora** [comment]
Good day @ssu2030 :)

The `OverlayScrollbarsComponent` is internally also using the `useOverlayScrollbars` hook, with the slight difference of how it uses the `initialize` function.

So what the `OverlayScrollbarsComponent` is doing differently is that it provides the `viewport` element, so that the library is not creating it, but instead it is taken from the markup created by react.

This is how I'm managing it to not re-write the complete library in `react`, `vue` or other frameworks, but instead just use their elements to initialize `OverlayScrollbars`. Its btw. not important that react (or any other library) knows about all elements a library created, its important that it knows about the "topmost" element (the target element) and (if needed) any element that can hold custom children. So for `OverlayScrollbars` this means that react needs to know about the `target` and about the `viewport` element, since the target is the topmost element and the viewport holds all the children.

Here is a an example of how the markup looks like before the initialization of the library:
```html
<div id="target">
  <p>The content</p>
  <span>some more content</span>
  ... and more content ...
</div>
```
and here the same example just after initialization:
```html
<div id="target">
  <div class="os-helper-element"></div>
  <div id="viewport">
    <p>The content</p>
    <span>some more content</span>
    ... and more content ...
  </div>
  <div class="os-horizontal-scrollbar"></div>
  <div class="os-vertical-scrollbar"></div>
</div>
```

In this case react doesn't care about all of the new elements, it only cares about `#target` and `#viewport`, all other elements won't be touched by react directly because the are created by the library.

So in order for your example to work you'll need to have the needed markup (the target element AND the viewport element) and also initialize the library in this way. You can take a look at the source code of the [OverlayScrollbarsComponent](https://github.com/KingSora/OverlayScrollbars/blob/master/packages/overlayscrollbars-react/src/OverlayScrollbarsComponent.tsx) if you wanna know how it does the initialization exactly.

**Comment by ssu2030** [comment]
Good day @KingSora  :)
Thank you so much for your detailed response and for clarifying the issues. I realize now that I misunderstood how useOverlayScrollbars interacts with DOM initialization. 

It seems my main issue was not fully understanding the initialization logic and the required DOM structure for OverlayScrollbars to function correctly.

Currently, I have updated the code to ensure that the values are correctly applied during the OverlayScrollbarsComponent initialization phase, and it is now working as intended. Thank you!

Thank you again for your patience and assistance 😄 

Best regards,
ssu2030
