### ISSUE TITLE
Unable to scroll outside the box

### ISSUE THREAD

**Issue by abhiraj-gaikwad** [KingSora/OverlayScrollbars#74]
When you are inside the overlay scrollbars box and you keep on scrolling (do not stop) even if you hit the top or the bottom of the box, browser window scroll is not activated. Only after you stop scrolling for a second you are able to scroll past the element.

The issue can be found in demo page itself:

https://kingsora.github.io/OverlayScrollbars/#!demos/styling

**Comment by hamed-ehtesham** [comment]
Hi,
it is default behavior of browser and is not specific to this library

**Comment by abhiraj-gaikwad** [comment]
Hi,
But this works fine in mobile browser, it switches from the plugin scroll to browser scroll without any delay.

**Comment by KingSora** [comment]
Good day!

@hamed-ehtesham already pointed out that it's the native behavior. You can actually test it yourself with the nesting demo: [https://kingsora.github.io/OverlayScrollbars/#!demos/nesting](https://kingsora.github.io/OverlayScrollbars/#!demos/nesting) below you have the native behavior and it should be exactly the same as the behavior with the plugin. 

Mobile-scrolling (swiping) and scrolling with the mouse-wheel are two completely different things, but since the plugin only hides the native scrollbars and provides native scroll-behavior there should also be no difference.
