### ISSUE TITLE
Website: comparison table is shown improperly on iPad

### ISSUE THREAD

**Issue by mrg0lden** [KingSora/OverlayScrollbars#79]
Hi! I’m a fan of this library impressively implemented library. 

While browsing the comparison table through my iPad I found this strange bug. I will try to investigate it further later on, but here’s the issue for now.

![A gif](https://user-images.githubusercontent.com/8347078/50207294-19cb6200-037f-11e9-980a-d031144a69f5.gif)

**Comment by KingSora** [comment]
Good day!

Yes, I'm aware of this "bug". I'm using `visibility: collapse` to achieve this table layout and it seems like browsers are handling this css property differently. If you read the [documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/visibility) of `collapse` it states that:

> For `<table>` rows, columns, column groups, and row groups, the row(s) or column(s) are hidden and the space they would have occupied is removed (as if display: none were applied to the column/row of the table). However, the size of other rows and columns is still calculated as though the cells in the collapsed row(s) or column(s) are present. This value allows for the fast removal of a row or column from a table without forcing the recalculation of widths and heights for the entire table.

If I would use `visibility: hidden` instead of `visibility collapse` the table layout would look like in your picture. This indicates that your browser is interpreting `visibility: collapse` as `visibility: hidden` even though it is used on table-elements.

It's not a bug of the plugin but rather a bug of the browser you are using. Nevertheless I'll try to change the table layout in the future so it doesn't depend on `visibility collapse`.

**Comment by KingSora** [comment]
I have now pushed a update. Please check it out again and tell me if its now rendered properly.

**Comment by mrg0lden** [comment]
@KingSora Well done! It's fixed now. BTW, the website is stunning. You surly are a talented UI designer.

**Comment by KingSora** [comment]
Thanks! I really appreciate your kind words.
