### ISSUE TITLE
Use OverlayScrollbars with Headroom

### ISSUE THREAD

**Issue by jcdenooy** [KingSora/OverlayScrollbars#80]
Hello,

I'm trying to get Headroom to play nice with OverlayScrollbars. Headroom listens to window by default, but when setting the os-host as element to listen, I still get errors. Anything I could check out/be referred to to get that working quicker from this side?

Thanks for your time!

**Comment by KingSora** [comment]
Good day!

Headroom needs the actual scrolling-element to work properly (because it needs to listen to the scroll events). As stated in the [documentation](https://kingsora.github.io/OverlayScrollbars/#!documentation/domelements), the element which is responsible for scrolling is the `viewport` element. So the fix is to simply pass the `viewport` element instead of the `host` element.

I've created a small example for you: https://jsfiddle.net/p5ewxcf7/1/

I hope I could help!

**Comment by jcdenooy** [comment]
Hi KingSora!

Thanks for the (superfast!) reply. Passing the viewport instead of the host indeed works...end of the day and my lack of Pure JS didn't help at that. Works like a charm now. Thanks for setting up the example as well 👍
