### ISSUE TITLE
the script throws a bug when used on a chat page

### ISSUE THREAD

**Issue by supercain** [KingSora/OverlayScrollbars#81]
Hi,

I implemented the script on my chat page and I found some serious bugs. As the messages start to populate the screen, a vertical scrollbar appears so you can scroll up and see older messages. However, by implementing the script the message screen gets stuck and you cant even select the text from the messages. I kinda fixed by setting a delay so the script initializes 1 or 2 seconds after all the content has loaded but now when a new message appears on screen it appears OUTSIDE the scrolling box. I tried all the options but nothing worked. I hope you can fix this problem.

Thank you.

**Comment by hamed-ehtesham** [comment]
Hi, i think i had same problem before [here](https://github.com/KingSora/OverlayScrollbars/issues/64)

i think wrapping your messages in a
```html
<div></div>
```
would solve your problem

**Comment by KingSora** [comment]
Good day!

Alright, it seems like you're appending your content to the incorrect element. 
The plugin generates its own DOM-Elements and you must append your content to the `os-content` element. I've explained it in more detail in the issue from @hamed-ehtesham [here](https://github.com/KingSora/OverlayScrollbars/issues/64#issuecomment-430903722).

To visualize my explanation I've created a few demos for you:

* This is the behavior without the plugin at all: [https://jsfiddle.net/3zef6n9c/](https://jsfiddle.net/3zef6n9c/)
Pretty straight forward, everything is working as it should.

* Now you've decided to use OverlayScrollbars and the whole thing looks like this: [https://jsfiddle.net/3zef6n9c/1/](https://jsfiddle.net/3zef6n9c/1/). It at least matches your description you posted above.

* The fixed version: [https://jsfiddle.net/3zef6n9c/2/](https://jsfiddle.net/3zef6n9c/2/). 
As you can see, I've only changed the element to which the messages are append to, nothing else.

----

Wrapping your whole content into a `div` element like @hamed-ehtesham mentioned would also solve the issue because you wouldn't need to change the element: 

* Before using OverlayScrollbars: [https://jsfiddle.net/3zef6n9c/3/](https://jsfiddle.net/3zef6n9c/3/).
* After using OverlayScrollbars: [https://jsfiddle.net/3zef6n9c/4/](https://jsfiddle.net/3zef6n9c/4/).
You see, I didn't had to make changes at all.

I hope this solves your issue and it's more clear now how the plugin behaves. Please also consider to read the "DOM Elements" [documentation](https://kingsora.github.io/OverlayScrollbars/#!documentation/domelements) for more information about the generated DOM elements.

**Comment by supercain** [comment]
Thank you for your answers. I did so from the beginning. My html markup is like this:

<div id="wrapper">
 <div id="inner">
   <div id="message1">something</div>
  <div id="message2">something</div>
  <div id="message3">something</div>
 </div>
</div>

I then executed the code like this:

var chatElm = $('#wrapper');
var osInstance = OverlayScrollbars(chatElm, { });

but it indeed behaves like this: https://jsfiddle.net/3zef6n9c/1/

I guess its related to the way my chat script behaves but I cant change that. By the way, my chat is a 123flashchat, the html5 version. 

Thank you.

**Comment by supercain** [comment]
Help please??

**Comment by KingSora** [comment]
I'm on vacation right now and wont be back until tomorrow. I'll help you as soon as possible.

Merry Christmas!

**Comment by KingSora** [comment]
I tried to look it up and see how 123flashchat works but I can't access any demo site with my developer tools open. It seems they have some sort of policy or something. Is it possible for you to send me a small demo of your site? I can't really help you else...

Sure, there are still possibilities to make it work, but they are more hacky than a real fix.

**Comment by supercain** [comment]
I will send you the link to my site if you want. Can I send you a private message from here?

**Comment by KingSora** [comment]
Please use my public E-Mail Adress: king-sora@hotmail.de

**Comment by KingSora** [comment]
A update on this issue:
We could together fix the issue. Thankfully it was not a bug, but rather a problem of the structure and css of the page.
