### ISSUE TITLE
Contenteditable & Text-dependent-width element collapses widthwise

### ISSUE THREAD

**Issue by joonaspaakko** [KingSora/OverlayScrollbars#82]
I could fix it by adding a static width to the host element, that I keep updating on `keyup`, but I'd like to avoid that.

Am I doing something wrong?

<kbd>[**Jsfiddle demo**](http://jsfiddle.net/lollero/n423vwth/)</kbd>

**This is an example of the desired behavior using native scrollbars:**

![2019-01-11 10 47 46](https://user-images.githubusercontent.com/1164476/51023160-e602e700-158e-11e9-842b-319090fa865b.gif)

**Example of the behavior when I attach OS:**

![2019-01-11 10 50 53](https://user-images.githubusercontent.com/1164476/51023218-0b8ff080-158f-11e9-997b-302d2efbdfee.gif)

**Comment by KingSora** [comment]
Good day!

Is it possible for you to use a `textarea` instead of a `contenteditable` div?
The problem here arises because the text defines the width of the container. This is problematic because your content gets wrapped by the plugin and `display: inline-block` element calculates its size dependent on the parent element. 

I have a workaround for this, but the cleaner, and in my opinion, correct solution would be to use a textarea.

I've created a fiddle demo for both:
- Contenteditable: [http://jsfiddle.net/nvjf0o98/1](http://jsfiddle.net/nvjf0o98/1)
- Textarea: [http://jsfiddle.net/nvjf0o98/2](http://jsfiddle.net/nvjf0o98/2)

**Note**: The textarea demo doesn't look right without the plugin initialized because the native textarea doesn't support `auto width` or `auto height`, but the plugin does.

**Comment by joonaspaakko** [comment]
I failed to mention that I need the parent element to be able to squeeze it as much as the text allows. 

Which is why I think I probably need to go with the more crude `contenteditable` method.

**When the parent element is resized, widthwise, the text container should resize with it:**
1. `textarea` : http://jsfiddle.net/lollero/35cbvhz9/5/
2. `contenteditable`: http://jsfiddle.net/lollero/m37zsref/4/
   - Now this works, but I wanted to ask if you think this too is risky of setup... given that I'm forcing `width: auto` to `.os-content-glue`

**Comment by joonaspaakko** [comment]
Yea, that's what I was thinking. Thanks.

**Comment by KingSora** [comment]
Glad I could help!

In case you are asking yourself why there is a overflow if you clear all your text and the div is empty - this seems to be a chrome bug. I've created a testcase [here](http://jsfiddle.net/2voL1d6h/) and reported the bug already to the chromium team [here](https://bugs.chromium.org/p/chromium/issues/detail?id=921471). It is working on firefox without a issue though.
