### ISSUE TITLE
Instance is not working

### ISSUE THREAD

**Issue by dslpp056193** [KingSora/OverlayScrollbars#83]
![image](https://user-images.githubusercontent.com/11080873/51257715-45129280-19b9-11e9-9bb0-d1c4859118d5.png)

Returns:
![image](https://user-images.githubusercontent.com/11080873/51257678-2d3b0e80-19b9-11e9-900c-7710742f5bc0.png)

**Comment by dslpp056193** [comment]
And initializing does not return an instance. It just return a jquery node element.

**Comment by KingSora** [comment]
Good day!

In order to not break the jQuery chain the initialization will return a jQuery object. 
So you can go cool stuff like this:
```javascript
$('#my-element').overlayScrollbars({ }).show();
```
To get the instance you have to call the method without parameters:
```javascript
var osInstance = $('#my-element').overlayScrollbars();
```
And if you want to initialize the plugin and return the instance you'll have to do this:
```javascript
var osInstance = $('#my-element').overlayScrollbars({ }).overlayScrollbars();
```

You can read more about initialization in the [documentation](https://kingsora.github.io/OverlayScrollbars/#!documentation/initialization-jquery).

**Comment by dslpp056193** [comment]
Ow. Not usual 😅. Thanks!

**Comment by KingSora** [comment]
Glad I could help!
