### ISSUE TITLE
Using OverlayScrollbars with scrolling libraries like AOS (Animate On Scroll)

### ISSUE THREAD

**Issue by edoardolunardi** [KingSora/OverlayScrollbars#85]
Hi! First of all, thank you for the awesome plugin. I want to include it in my project which uses this for scrolling animations https://michalsnik.github.io/aos/

The problem is that my content is no longer displayed, probably due to some properties that OverlayScrollbars is applying to the body.

Any solutions? Thank you.

**Comment by KingSora** [comment]
Good day!

The problem here is, that AOS is using the `window` element to detect scroll events. 
If you use OverlayScrollbars on your body element, it gets wrapped by genereated elements. And due to these elements, the `window` element will never receive a `scroll` event. 
AOS would need to implement a possibility (option) to pass a other element as the `window` element to listen to `scroll` events. Then you could pass the `os-viewport` element to it and everything would work.

**Comment by edoardolunardi** [comment]
Thank you for the response!
