### ISSUE TITLE
Sticky element breaking when scrollbar is applied to the body element

### ISSUE THREAD

**Issue by scarroll142** [KingSora/OverlayScrollbars#89]
If you are using position: sticky on an element and the scrollbar is applied to a parent of that element, the element will stop being sticky after you have scrolled the height of your screen. The issue does not appear when using the native scrollbar. Tested in chrome, edge, and firefox and all of the results were the same. Additionally, position: sticky is fine when the scrollbar is applied to an element that is not the parent of the sticky positioned element.

**Comment by KingSora** [comment]
Good day!

This case is a bit... unlucky.
You see, OverlayScrollbars is using 100% height if it is applied on the `body` element. 
If I imitate this on the native body element, I'll get the same result:
- Native: https://jsfiddle.net/ajodLzk5/
- Plugin: https://jsfiddle.net/bj9k4zeo/

The solution would be easy, just change the height to `auto` on the `body` element for native and on the first `os-content` element for plugin:
- Native: https://jsfiddle.net/xrn70L8q/
- Plugin: https://jsfiddle.net/2uoz3v1w/

Thats basically the fix / workaround. 
I've used `100%` height here because I've never run into troubles or something, and the `position: sticky` CSS property wasn't a confirmed standard as I started the development on the plugin.

I'm not quite sure how to implement this properly so you wont have to do this yourself manually everytime you wanna use `position: sticky`. I guess I'll implement a standard rule in the CSS of the plugin so you will just have to apply a certain class to your body element. The fix will look something like this (class name isn't finally decided yet):
```CSS
body.os-host.os-host-sitcky > .os-padding > .os-viewport > .os-content {
  height: auto !important;
}

```

**Comment by scarroll142** [comment]
Well that certainly makes sense to me. Thanks for the help and getting me out of this... sticky situation.

**Comment by KingSora** [comment]
Höhöhöööö nice pun there :D

**Comment by vblanton** [comment]
Hello, i see that this issue is closed, but still having the same situation. Has the workaround changed since this was first reported?

**Comment by vblanton** [comment]
@KingSora Hello

The issue is in NextJS/React app that uses tailwind as well. Essentially, adding overlayscrollbar to the body element, while having a <header> element  w/ sticky along the top of the page. the header element's stickyness is dropped while the body scrolls. Here is a simple example in jsfiddle:

https://jsfiddle.net/wg7yeLto/

**Comment by KingSora** [comment]
@vblanton I've re-created the example on stackblitz (using just react without next.js) here: https://stackblitz.com/edit/vitejs-vite-46twghvd?file=src%2FApp.tsx,src%2Findex.css&terminal=dev and I'm not observing any issues..

**Comment by ricardohsweiss** [comment]
Hi, my good fellows,

I am trying to achieve a position sticky on an element inside the OverflowScrollbar component, but without success, I know there is an issue when trying to add to the body element, but in my case, I have a tab, where inside the tab there is a header, and this header that should be sticky.

I've forked your working react example with the header, and tweaked it to try to achieve the same behavior but targeting a custom div instead of the body

https://stackblitz.com/edit/vitejs-vite-pubaa51u?file=src%2FApp.tsx,src%2Findex.css&terminal=dev

I appreciate the attention on this matter and love using the lib so far!

**Comment by ricardohsweiss** [comment]
Hi, my good fellows,

Sorry for commenting on this closed issue, but I am trying to achieve a position sticky on an element inside the OverflowScrollbar component, I know there is an issue when trying to add to the body element, but in my case, I have a tab, where inside the tab there is a header, and this header that should be sticky.

I've forked your working react example with the header and tweaked it to try to achieve the same behavior but targeting a custom div instead of the body but without success

https://stackblitz.com/edit/vitejs-vite-pubaa51u?file=src%2FApp.tsx,src%2Findex.css&terminal=dev

I appreciate the attention on this matter and love using the lib so far!

**Comment by KingSora** [comment]
Good day @ricardohsweiss :)

The problem here is that `#containerToBeScrollable` has no limiting height, so its growing with its content. If you limit its height with e.g. `max-height: 100vh` the sticky position is working in your example: https://stackblitz.com/edit/vitejs-vite-t3uak84h?file=src%2FApp.tsx&terminal=dev

**Comment by KingSora** [comment]
@ricardohsweiss in your example the `OverlayScrollbarsComponent` would be a drop-in replacement for `#containerToBeScrollable`: https://stackblitz.com/edit/vitejs-vite-rxtfksez?file=src%2FApp.tsx&terminal=dev
