### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by trystanclarke** [KingSora/OverlayScrollbars#90]
First of all, great job with this library it is great to use and works nicely, so thanks for your hard work.

I would like to let you know that I am getting an error firing in window.onerror relating to the ResizeObserver since adding overlay scrollbars.  This happens on chrome only and happens when elements are added and removed from the dom inside the scrolled element.  It seems to happen when there is both an addition and removal of an element at the same time.
This doesn't seem to affect functionality so for the moment I am just suppressing this particular error but I thought you might want to take a look.
Searching around this error it looks like this can be an issue with chrome since chrome 64 and the workaround seems to be to throttle the callback function used in the ResizeObserver - see example in this thread https://github.com/d6u/react-container-query/issues/70

Kind Regards,

Trystan

**Comment by KingSora** [comment]
Good day!

Thanks for this, I'll try my best to resolve it. 
Although I don't really like the `requestAnimationFrame` "fix", because it just looks silly and it doesn't really solve it. I've created a fiddle so you (and maybe others) have a bit more insight about this:
- current version: https://jsfiddle.net/ko3rh78f/
- "fixed" version: https://jsfiddle.net/ko3rh78f/1/

Wrapping all the content of my callback method inside a `requestAnimationFrame` callback can't be really called a fix (in my opinion). I'll investigate in this a bit more if I have more time, but for now I'll leave it like this.

I've also found this useful answer: 

> ﻿This error means that ResizeObserver was not able to deliver all observations within a single animation frame. It is benign (your site will not break).

Which was posted in this StackOverflow thread: https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded

**Comment by trystanclarke** [comment]
Thanks for taking a look, I know what you mean about using requestAnimationFrame.

**Comment by nickensoul** [comment]
@KingSora thanks for your attention!
any news? what do you think about this one year later?

**Comment by KingSora** [comment]
@nickensoul well, my opinion hasn't really changed..

**Comment by lazuee** [comment]
I get **ResizeObserver loop limit exceeded** issue when i add flexbox css to the parent of the div child that i used for a slider image. Can someone tell me how do i fix it? I used "Swiper" btw.

~~> https://swiperjs.com/

**Comment by Elringus** [comment]
In case anyone struggling with this error shown in webpack overlay, you can mute it like this:

```js
// webpack.config.js
devServer: {
    client: {
        overlay: { runtimeErrors: e => e.message !== "ResizeObserver loop limit exceeded" }
    }
}
```
