### ISSUE TITLE
Print media

### ISSUE THREAD

**Issue by bytestream** [KingSora/OverlayScrollbars#91]
What's the best way to handle printing a page with overlay scrollbars initialised on it? The overflow prevents the full content of the element from being visible in print media

Destroy the scrollbars using the onbeforeprint event? https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeprint

**Comment by KingSora** [comment]
Good day!

I'm assuming you're using OverlayScrollbars on your body element. 
To be honest, I haven't tried printing until now, but it seems like you don't have another choice but destroying it and re-initializing it after the print. (this applies only to the body element, every other element should be fine)

**Comment by bytestream** [comment]
OK thanks!

**Comment by Reverier-Xu** [comment]
Good day!

Sorry for replying to such a long-ago post, I've tried out another effective way:

you can use `@media print` to set the style of `overlay-scrollbars-component` to `height: auto` (it should be `height: 100%` or some other specified height), so that the content will prop up the container and use the browser native scrolling, and printing will work properly.
