### ISSUE TITLE
Bottom event

### ISSUE THREAD

**Issue by boukenka** [KingSora/OverlayScrollbars#92]
Hello,

I have tried and searched during a long time a 'good' scrollbar.
This one is definitively the best. I have a small issue with it.
Below is my coding to implement the logic of an 'infinite' scroll in a datatable:

```javascript
var instance = $(selector).overlayScrollbars(
{
	className: overlayScrollbarsTheme,
	resize: "none",
	sizeAutoCapable: true,
	autoUpdate: true,
	normalizeRTL: true,
	scrollbars : 
	{
         visibility: "auto",
         autoHide: "leave",
         autoHideDelay: 500,
	},
	callbacks : 
	{
          // gets fired after every scroll. 
          onScroll: function() 
          { 
	    // get the position of the scrollbar
	    var scrollInfo = instance.scroll();

	    // check if the scrollbar has reached the bottom
	    if (scrollInfo.position.y === scrollInfo.max.y)
	    {
               getNextCommunications(instance);
	    }
           },
	}
}).overlayScrollbars();
```

Each time the scrollbar reaches the bottom, the event is triggered.
How can I prevent this event from being triggered multiple times when the scrollbar 
has reached the bottom and the getNextCommunication method is called? I would need only once.
The getNextCommunications function calls an AJAX script and runs asynchronously.
I have tried the following but this is not working:
```javascript
instance.scroll({ y : "-= 10px"  });
```

Thanks for any answer.

**Comment by boukenka** [comment]
One solution would be to use the following event, I guess?

```javascript
onScrollStop: function() 
```

**Comment by KingSora** [comment]
Good day!

Well, this is something you have to implement by yourself. 
Since the plugin is offering you only callbacks which has to do with, well, scrolling there isn't any specific callback which is firing once if you need it. The `onScrollStop` callback could be a good start, but the user has to stop scrolling for a few milliseconds, so this callback would fire.

I've tried my own approach to this, maybe this can be a guide to you: https://jsfiddle.net/da30pu9s/1/

As you can see, I'm working with the regular `onScroll` callback but I'm restricting the `getNextCommunications` method from beeing called with a variable called `ajaxIsLoading` which is set to `true` once a ajax call starts and set to `false` if this ajax call finishes. I think the rest of the code is kind of self explanatory... If not, you can ask me anything you want.

**Comment by boukenka** [comment]
Thank you for the quick reply and the advice. 
I will try to implement it tomorrow.
Have a good nignt!

**Comment by boukenka** [comment]
Hello,

Finally I have implemented the following coding below. 
It is solving my issue. 
What do you think to implement properties 'bottomReached' or 'topReached'?

```javascript
// define the reference selector of the scrollbars
var bottomReached = false;

var instance = $(selector).overlayScrollbars(
{
	className: overlayScrollbarsTheme,
	resize: "none",
	sizeAutoCapable: true,
	autoUpdate: null,
	normalizeRTL: true,
	scrollbars : 
	{
          visibility: "auto",
	  autoHide: "leave",
	  autoHideDelay: 500,
	},
	callbacks : 
	{
	  // gets fired when scroll is stopped 
	  onScroll: function() 
	  { 
	    // get the position of the scrollbar
	    var scrollInfo = instance.scroll();

	    // check if the scrollbar has reached the bottom
	    if (scrollInfo.position.y !== scrollInfo.max.y)
	    {
	       bottomReached = false;
	    }
	    else
	    {
	       // check if bottom has been already reached by the scrollbar
	       // so the function is not called multiple times
	       if (!bottomReached)
	       {
	         bottomReached = true;
	         getNextCommunications();
	       }
	     }
	  },
	}
}).overlayScrollbars();
```

**Comment by KingSora** [comment]
Your suggested properties are actually implemented within the `scrollInfo` object which you can get with the `.scroll()` method. With `scrollInfo.ratio.y === 0` you know you are on the top and with `scrollInfo.ratio.y === 1` you know you are on the bottom. The same works actually with the horizontal axis. I don
t think separate properties are necessary for this.

**Comment by boukenka** [comment]
Thanks for the information and for the feedback.

**Comment by KingSora** [comment]
A little feedback here. In chrome for android the `scrollTop` and `scrollLeft` values returns a `float` instead of a `int`.
Yor check `scrollInfo.position.y !== scrollInfo.max.y` can therefore be wrong, even if you're on the bottom, because `scrollInfo.position.y` can be for example `500.123` but `scrollInfo.max.y` is `500`, since the max value is calculated from the values of `scrollHeight` (or width) and `clientHeight` (or width) which both can only return `int` values. 

The value `scrollInfo.ratio.y`, on the other hand, can be trusted, since I'm limiting this value to maximum `1` and minimum `0`. So the check `scrollInfo.ratio.y === 1` is safer and the way to go.

**Comment by boukenka** [comment]
Thanks for the advice ☺️ 
I have updated my coding accordingly.
Have a nice sunday.
